/* COSMIC WEAVER shooting-script library. 30 transmissions across 5 pillars. */

export const PILLARS = {
  launch: { label: 'LAUNCH', color: '#FF2E63', description: 'The first five uploads. Retention-engineered, loop-first, upload kit included.', cadence: 'day 1-9, one every 48h' },
  transmission: { label: 'TRANSMISSION', color: '#00FFFF', description: 'Mind-blowing space fact, witnessed first-person from out there.', cadence: '3x per week' },
  mystery: { label: 'MYSTERY', color: '#FFB000', description: 'Unsolved cosmic questions told by someone living inside them.', cadence: '2x per week' },
  answers: { label: 'ANSWERS', color: '#00FF41', description: 'VEYL replies to Earth comments, always in character.', cadence: '1-2x per week' },
  lore: { label: 'LORE DROP', color: '#FF1A1A', description: 'Who VEYL is. Cliffhangers only. 1 in every 8-10 videos.', cadence: '1 per 8-10 videos' },
  trend: { label: 'TREND HIJACK', color: '#B366FF', description: 'Trending formats performed from a nebula. Contrast stops the scroll.', cadence: 'when a trend fits' },
};

export const HOOK_BANK = [
  'They told you space is silent. They lied.',
  'I am four light-years away. Listen closely.',
  'Your sun looks different from here.',
  'Something answered. It was not supposed to.',
  'You are being watched by everything you see.',
  'The universe has a sound. I have heard it.',
  'This transmission may not reach you in time.',
  'Every star you see might already be dead.',
  'I found something older than light.',
  'Do not trust the darkness between stars.',
  'Earth looks so small from this rock.',
  'I ran out of reasons to come home.',
  'The silence out here has a texture.',
  'Your planet glows louder than you think.',
  'There is a hole in the sky here.',
  'I counted the stars. One was missing.',
  'Someone built this station. No one stayed.',
  'The suit keeps me alive. Barely.',
  'You asked what I am. Wrong question.',
  'Time moves differently where I am standing.',
];

export const TITLE_FORMULAS = [
  'Why I Can Never {verb} {noun}',
  'What {noun} Actually Sounds Like',
  'The {adjective} Thing I Found In {place}',
  '{number} Seconds From {place}, Something Moved',
  'You Are Looking At {noun} Wrong',
  'The Question NASA Will Not Answer About {noun}',
];

const B = (t, text, emote = 'neutral', fx = 'none', note = '') => ({ t, text, emote, fx, note });

export const TRANSMISSIONS = [
  // ============ PILLAR: TRANSMISSION (1-10) ============
  {
    id: 1, number: 1, pillar: 'transmission', title: 'I Broadcast From 4 Light-Years Away', world: 'nebula-drift', durationSec: 38,
    hook: 'They told you space is silent. They lied.',
    beats: [
      B(0, 'They told you space is silent. They lied.', 'neutral', 'none', 'lean into lens, dead still'),
      B(4, 'My name is VEYL. I am speaking from past your sun. Far past it.', 'scan', 'none', 'slow head turn'),
      B(11, 'These words took four years to reach you. I said them before you found this channel.', 'smirk', 'zoom', 'punch in'),
      B(19, 'From here, your whole world is one blue dot. Everyone you love fits inside it.', 'sad', 'none', 'look off to side'),
      B(27, 'I will show you what you cannot see from down there. One transmission at a time.', 'surge', 'pulse', 'energy up'),
    ],
    loopLine: 'Stay close to the signal. It is the only thing keeping me... here.',
    caption: 'Transmission #1 from somewhere past Proxima. #space #veyl #cosmicweaver #shorts #scifi',
    pinnedComment: 'First question, Earth: if you could ask someone stranded in deep space one thing — what is it?',
    factCheck: 'Proxima Centauri is ~4.24 light-years away; light (and radio) takes 4.24 years to travel it.',
  },
  {
    id: 2, number: 2, pillar: 'transmission', title: 'What A Black Hole Actually Sounds Like', world: 'dying-star', durationSec: 40,
    hook: 'The universe has a sound. I have heard it.',
    beats: [
      B(0, 'The universe has a sound. I have heard it.', 'neutral', 'none', 'whisper energy'),
      B(5, 'There is a black hole out here that hums. One single note. Never stopping.', 'scan', 'none', ''),
      B(12, 'The note is B flat. Deeper than any piano key ever made.', 'smirk', 'zoom', 'tap the numbers'),
      B(19, 'It is real sound. Hot gas carries it, like air carries your voice. Just too deep to hear.', 'neutral', 'none', ''),
      B(29, 'It has been holding that one note for two and a half billion years.', 'shock', 'flare', 'pause after'),
    ],
    loopLine: 'And it is still singing right now. While you watch this. Listen again.',
    caption: 'A black hole has been humming one note for 2.5 billion years. #blackhole #space #veyl #shorts',
    pinnedComment: 'If you could hear one sound from space, what would you choose?',
    factCheck: 'Perseus cluster black hole emits pressure waves at B-flat, ~57 octaves below middle C (NASA Chandra, 2003).',
  },
  {
    id: 3, number: 3, pillar: 'transmission', title: 'You Are Looking At The Past Right Now', world: 'asteroid-earth', durationSec: 36,
    hook: 'Every star you see might already be dead.',
    beats: [
      B(0, 'Every star you see might already be dead.', 'neutral', 'none', 'still, cold open'),
      B(5, 'Starlight takes years to reach you. Sometimes thousands of years.', 'scan', 'none', ''),
      B(11, 'The light hitting your eyes tonight left its star before your city existed.', 'neutral', 'zoom', ''),
      B(19, 'You have never seen the sky as it is. Only as it was.', 'sad', 'none', 'slow down'),
      B(26, 'Looking up is time travel. You do it every night. For free.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'So when you look up tonight — remember something out there is looking back. At your past.',
    caption: 'The night sky is a photograph of the past. #space #timetravel #veyl #shorts',
    pinnedComment: 'The light from which star died before it reached you? Wrong answers only.',
    factCheck: 'Lookback time: starlight takes years-to-millennia to arrive; we always observe the past.',
  },
  {
    id: 4, number: 4, pillar: 'transmission', title: 'I Cannot Find Your Sun From Here', world: 'nebula-drift', durationSec: 35,
    hook: 'I counted the stars. One was missing.',
    beats: [
      B(0, 'I counted the stars. One was missing.', 'neutral', 'none', ''),
      B(5, 'Yours. From out here, your sun is nothing special.', 'scan', 'none', 'look around'),
      B(12, 'It is one faint dot lost in two hundred billion others.', 'neutral', 'zoom', ''),
      B(19, 'Everything you have ever loved orbits a star nobody out here would notice.', 'sad', 'none', 'let it land'),
      B(27, 'That is not sad. That is camouflage.', 'smirk', 'glitch', 'sharp tone shift'),
    ],
    loopLine: 'Maybe being unnoticed is the only reason you are still safe. Count your stars again.',
    caption: 'Your sun is invisible from where I am. #sun #space #veyl #shorts #cosmicweaver',
    pinnedComment: 'Question for Earth: is being cosmically invisible a blessing or a prison?',
    factCheck: 'The Sun is an ordinary G-type star, invisible to the naked eye beyond ~60 light-years.',
  },
  {
    id: 5, number: 5, pillar: 'transmission', title: 'One Hour Here Costs You Seven Years', world: 'dying-star', durationSec: 40,
    hook: 'Time moves differently where I am standing.',
    beats: [
      B(0, 'Time moves differently where I am standing.', 'neutral', 'none', ''),
      B(5, 'Near heavy gravity, clocks run slow. Not broken. Slow. This is measured fact.', 'scan', 'none', ''),
      B(13, 'On a planet near a black hole, one hour there is seven years back home.', 'shock', 'zoom', ''),
      B(21, 'You use this every day. GPS clocks run fast in orbit. They get fixed daily. Or maps break.', 'neutral', 'none', ''),
      B(31, 'So ask yourself. Compared to someone, somewhere — how old are you really?', 'smirk', 'pulse', ''),
    ],
    loopLine: 'I have been out here longer than you think. Or maybe... not long at all.',
    caption: 'Gravity bends time. Your GPS proves it daily. #interstellar #timedilation #veyl #shorts',
    pinnedComment: 'Would you trade seven years on Earth for one hour out here? Answer honestly.',
    factCheck: 'Gravitational time dilation (general relativity); GPS satellites correct ~38 microseconds/day.',
  },
  {
    id: 6, number: 6, pillar: 'transmission', title: 'Space Is Not Empty. I Am Swimming In It', world: 'nebula-drift', durationSec: 37,
    hook: 'Do not trust the darkness between stars.',
    beats: [
      B(0, 'Do not trust the darkness between stars.', 'neutral', 'none', ''),
      B(5, 'It is not empty. Right now I am moving through dust, and gas, and wind.', 'scan', 'none', 'gesture around'),
      B(13, 'Your sun breathes fire in every direction. A wind made of pieces of the sun itself.', 'surge', 'shake', ''),
      B(21, 'That wind is why comets have tails. It is touching the top of your sky right now.', 'neutral', 'none', ''),
      B(29, 'The void is not a void. It is an ocean.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'And I am somewhere in the deep end. Do not trust the darkness.',
    caption: 'The "vacuum" of space is an ocean of plasma. #solarwind #space #veyl #shorts',
    pinnedComment: 'If space is an ocean, what do you think swims in it?',
    factCheck: 'Solar wind streams at 300-800 km/s; the interstellar medium contains plasma and dust.',
  },
  {
    id: 7, number: 7, pillar: 'transmission', title: 'Sunsets Here Are Blue', world: 'red-planet', durationSec: 34,
    hook: 'Your planet glows louder than you think.',
    beats: [
      B(0, 'I watched a sunset today. It was blue.', 'neutral', 'none', 'calm, sitting energy'),
      B(5, 'On Mars, the dust in the air bends light the opposite way your air does.', 'scan', 'none', ''),
      B(12, 'Your sky is blue and your sunsets are red. There, the sky is red. The sunsets are blue.', 'neutral', 'zoom', ''),
      B(21, 'Same light. Same star. Opposite goodbye.', 'sad', 'none', 'long pause'),
    ],
    loopLine: 'Somewhere, every sunset you have ever seen is still traveling. Blue side out.',
    caption: 'Martian sunsets are blue. Really. #mars #sunset #veyl #shorts #space',
    pinnedComment: 'Blue sunset or red sunset — which universe would you rather live in?',
    factCheck: 'Mars sunsets appear blue: fine dust scatters red light and lets blue through near the sun (NASA rover images).',
  },
  {
    id: 8, number: 8, pillar: 'transmission', title: 'A Teaspoon Of This Star Outweighs A Mountain', world: 'dying-star', durationSec: 38,
    hook: 'I found something heavier than everything you know.',
    beats: [
      B(0, 'I found something heavier than everything you know.', 'neutral', 'none', ''),
      B(5, 'When a giant star dies, it crushes itself into a ball the size of a city.', 'scan', 'none', ''),
      B(12, 'One teaspoon of that ball weighs four billion tons.', 'shock', 'zoom', 'hit the number'),
      B(19, 'That is every human on Earth, squeezed into a sugar cube.', 'neutral', 'flare', ''),
      B(26, 'And some of them spin seven hundred times every second. While weighing that much.', 'surge', 'shake', ''),
    ],
    loopLine: 'The universe does not break its own rules. It just writes ones you cannot imagine.',
    caption: 'A teaspoon of neutron star: 4 billion tons. #neutronstar #space #veyl #shorts',
    pinnedComment: 'What is the heaviest thing you can imagine? The universe laughs at it.',
    factCheck: 'Neutron star density ~10^17 kg/m³; millisecond pulsars spin 700+ times/sec.',
  },
  {
    id: 9, number: 9, pillar: 'transmission', title: 'Space Has A Smell. I Know It Too Well', world: 'derelict-station', durationSec: 36,
    hook: 'The silence out here has a texture.',
    beats: [
      B(0, 'The silence out here has a texture. And a smell.', 'neutral', 'none', ''),
      B(6, 'Every astronaut who ever stepped outside says the same thing.', 'scan', 'none', ''),
      B(12, 'Burnt steak. Hot metal. Gunpowder. Stuck to their suits.', 'neutral', 'zoom', ''),
      B(19, 'It is space itself, slowly burning the fabric. The way rust burns iron.', 'narrow', 'static', ''),
      B(27, 'The universe smells like something burning. Because it is.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'This station smells like it too. Which is strange. Because nothing here has burned... yet.',
    caption: 'Astronauts say space smells like burnt metal and gunpowder. #space #veyl #shorts',
    pinnedComment: 'What do you imagine a dying star smells like? I will tell you if you are close.',
    factCheck: 'Astronauts consistently report a burnt/metallic odor on suits after EVAs (atomic oxygen reactions).',
  },
  {
    id: 10, number: 10, pillar: 'transmission', title: 'The Machine That Will Outlive Your Species', world: 'asteroid-earth', durationSec: 40,
    hook: 'Something you built will outlive everything you know.',
    beats: [
      B(0, 'Something you built will outlive everything you know.', 'neutral', 'none', ''),
      B(6, 'In 1977 you threw a machine off your planet. It never came back. It never will.', 'scan', 'none', ''),
      B(14, 'It left your solar system while you were arguing on the internet.', 'smirk', 'zoom', ''),
      B(21, 'In forty thousand years it reaches another star. Your cities will be dust. It will still be flying.', 'sad', 'none', ''),
      B(30, 'It carries a golden record of Earth sounds. A hello, from people who will be long gone.', 'neutral', 'flare', 'soften'),
    ],
    loopLine: 'I have seen it out here. I did not wave. It would not have mattered.',
    caption: 'Voyager 1 will outlive us all. It carries our voice. #voyager #space #veyl #shorts',
    pinnedComment: 'If YOU could put one sound on the golden record, what would it be?',
    factCheck: 'Voyager 1 entered interstellar space in 2012; passes near star AC+79 3888 in ~40,000 years; carries the Golden Record.',
  },

  // ============ PILLAR: MYSTERY (11-18) ============
  {
    id: 11, number: 11, pillar: 'mystery', title: 'Where Is Everybody? I Checked', world: 'nebula-drift', durationSec: 42,
    hook: 'Two hundred billion stars. And nobody is home.',
    beats: [
      B(0, 'Two hundred billion stars in this galaxy. And nobody is home.', 'neutral', 'none', ''),
      B(7, 'The math says thousands of alien worlds should exist. The sky says zero.', 'scan', 'none', ''),
      B(15, 'Your scientists have a fancy name for it. Out here, we just call it the Quiet.', 'narrow', 'static', ''),
      B(23, 'Maybe life is rare. Maybe it hides. Maybe something removes it before it gets loud.', 'neutral', 'zoom', 'slow'),
      B(33, 'I have traveled far enough to have an opinion.', 'smirk', 'glitch', ''),
    ],
    loopLine: 'And my opinion is: keep your volume down. Two hundred billion stars heard that.',
    caption: 'The Fermi Paradox, from someone who went looking. #fermiparadox #space #veyl #shorts',
    pinnedComment: 'Why do YOU think the universe is silent? Best theory gets answered in a transmission.',
    factCheck: 'Fermi paradox: tension between high probability estimates of ET life and absence of evidence.',
  },
  {
    id: 12, number: 12, pillar: 'mystery', title: 'The Great Filter May Be Behind You', world: 'asteroid-earth', durationSec: 41,
    hook: 'There is a wall every civilization hits. Most never pass it.',
    beats: [
      B(0, 'There is a wall every civilization hits. Most never pass it.', 'neutral', 'none', ''),
      B(6, 'Some deadly test that almost nothing in the universe survives. A filter.', 'scan', 'none', ''),
      B(13, 'Here is the question that should keep you awake tonight. Is the wall behind you... or ahead?', 'narrow', 'zoom', ''),
      B(22, 'If it is behind you, you are a miracle. The sky is empty because you made it.', 'neutral', 'none', ''),
      B(31, 'If it is ahead — the silence out here is a warning.', 'anger', 'static', 'cold'),
    ],
    loopLine: 'I have seen what is ahead. Transmission twenty-six is where I stop being polite about it.',
    caption: 'The Great Filter: humanity\'s scariest question. #greatfilter #space #veyl #shorts',
    pinnedComment: 'Filter behind us or ahead of us? Defend your answer, Earth.',
    factCheck: 'Great Filter hypothesis (Robin Hanson, 1996) — a step in evolution that few civilizations survive.',
  },
  {
    id: 13, number: 13, pillar: 'mystery', title: 'What Is At The Edge Of The Universe', world: 'nebula-drift', durationSec: 40,
    hook: 'I flew toward the edge of the universe. Here is the problem.',
    beats: [
      B(0, 'I flew toward the edge of the universe. Here is the problem.', 'neutral', 'none', ''),
      B(7, 'There is no edge. Whichever way you fly, the universe grows away from you.', 'scan', 'none', ''),
      B(15, 'Space itself stretches. Far away, it stretches faster than light. Nothing can outrun it.', 'neutral', 'zoom', ''),
      B(24, 'The farthest thing you can see is not a wall. It is how far back in time you can look.', 'narrow', 'none', ''),
      B(31, 'The edge of the universe is not a place. It is a deadline.', 'sad', 'pulse', 'let it sit'),
    ],
    loopLine: 'And every second, more of it slips past that deadline. Forever out of reach. Even mine.',
    caption: 'There is no edge — only a horizon you can never catch. #universe #space #veyl #shorts',
    pinnedComment: 'If you could see one thing beyond the horizon, what would you want it to be?',
    factCheck: 'Metric expansion: distant regions recede superluminally; observable universe bounded by a cosmological horizon.',
  },
  {
    id: 14, number: 14, pillar: 'mystery', title: 'The Universe Could End Mid-Senten', world: 'dying-star', durationSec: 39,
    hook: 'The universe could end before I finish this sentence.',
    beats: [
      B(0, 'The universe could end before I finish this sentence.', 'neutral', 'none', 'dead calm'),
      B(6, 'Empty space might not be stable. It might just be... resting.', 'scan', 'none', ''),
      B(13, 'If one single point ever snaps, a bubble of new rules spreads at the speed of light.', 'narrow', 'zoom', ''),
      B(22, 'It rewrites everything it touches. Including you. And there is no warning. The warning arrives with it.', 'shock', 'static', ''),
      B(32, 'The good news? You would never know.', 'smirk', 'glitch', ''),
    ],
    loopLine: 'The better news? It has not happened for fourteen billion years. Probably... start the sentence again.',
    caption: 'Vacuum decay: the end that arrives at light speed. #vacuumdecay #physics #veyl #shorts',
    pinnedComment: 'Sleep well, Earth. Question: what would you do with one guaranteed last day?',
    factCheck: 'False vacuum decay is a hypothesized possibility if the Higgs vacuum is metastable.',
  },
  {
    id: 15, number: 15, pillar: 'mystery', title: '85 Percent Of Everything Is Missing', world: 'nebula-drift', durationSec: 40,
    hook: 'Most of the universe is missing. I am flying through the missing part.',
    beats: [
      B(0, 'Most of the universe is missing. I am flying through the missing part.', 'neutral', 'none', ''),
      B(7, 'Galaxies spin too fast. They should fly apart. Something invisible holds them together.', 'scan', 'none', ''),
      B(15, 'It is called dark matter. Most of everything that exists. And no one has ever seen it.', 'narrow', 'zoom', ''),
      B(24, 'It is passing through you right now. Through your walls. Through your planet. Silent.', 'neutral', 'static', ''),
      B(32, 'You are the rare kind of matter. The kind that can be seen.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'Which means the universe is mostly made of things that never look back. Mostly.',
    caption: '85% of matter has never been seen. It\'s passing through you now. #darkmatter #veyl #shorts',
    pinnedComment: 'If dark matter could think, what do you suppose it thinks of you?',
    factCheck: 'Dark matter ~85% of matter content; inferred from galaxy rotation curves and lensing.',
  },
  {
    id: 16, number: 16, pillar: 'mystery', title: 'What Falling Into A Black Hole Looks Like', world: 'dying-star', durationSec: 42,
    hook: 'From the outside, you never see anyone fall in. Ever.',
    beats: [
      B(0, 'From the outside, you never see anyone fall into a black hole. Ever.', 'neutral', 'none', ''),
      B(7, 'To you, watching, they slow down. Freeze. Fade. Stuck at the edge forever.', 'scan', 'zoom', ''),
      B(15, 'But for them? They fall right through in seconds. No wall. No flash. Just... no way back.', 'narrow', 'none', ''),
      B(24, 'Then gravity pulls them into a noodle of atoms. Scientists really call it spaghettification.', 'shock', 'shake', ''),
      B(33, 'Frozen forever. Gone in seconds. Both stories are true.', 'neutral', 'static', ''),
    ],
    loopLine: 'The universe does not agree on what happened to you. Think about that... forever.',
    caption: 'You freeze forever AND fall in seconds. Both true. #blackhole #relativity #veyl #shorts',
    pinnedComment: 'Which version scares you more — freezing forever, or crossing without noticing?',
    factCheck: 'Gravitational time dilation at event horizons; tidal spaghettification; both descriptions are frame-dependent and real.',
  },
  {
    id: 17, number: 17, pillar: 'mystery', title: 'The Signal That Repeats Every 16 Days', world: 'derelict-station', durationSec: 41,
    hook: 'Something out here is sending the same signal. On a schedule.',
    beats: [
      B(0, 'Something out here is sending the same signal. On a schedule.', 'neutral', 'none', ''),
      B(7, 'A flash of radio, shorter than a blink. Stronger than your sun on its worst day.', 'scan', 'none', ''),
      B(15, 'It repeats every sixteen days. Exactly. Like clockwork. For years now.', 'narrow', 'zoom', ''),
      B(23, 'Probably a dead star. A magnet so strong it screams. Probably.', 'neutral', 'static', ''),
      B(30, 'But out here, when something keeps perfect time... you check who is holding the clock.', 'anger', 'glitch', ''),
    ],
    loopLine: 'I have started counting the days. We are on day fifteen. Transmission continues tomorrow.',
    caption: 'FRB 180916: a cosmic signal on a 16-day loop. #frb #spacemystery #veyl #shorts',
    pinnedComment: 'Natural clock or someone\'s clock? Vote in the comments. I read everything.',
    factCheck: 'FRB 180916.J0158+65 repeats on a ~16.35-day cycle (CHIME, 2020); leading explanation involves magnetars/binaries.',
  },
  {
    id: 18, number: 18, pillar: 'mystery', title: 'The Star That Kept Turning Off', world: 'nebula-drift', durationSec: 40,
    hook: 'A star kept dimming. In patterns no planet can make.',
    beats: [
      B(0, 'A star kept turning off. In patterns no planet can make.', 'neutral', 'none', ''),
      B(6, 'It kept losing a fifth of its light. At random. No rhythm. All wrong.', 'scan', 'none', ''),
      B(14, 'For a while, real scientists said the words alien megastructure out loud. In real papers.', 'smirk', 'zoom', ''),
      B(23, 'The best answer now is dust. A broken comet. A shredded moon. Probably.', 'neutral', 'none', ''),
      B(31, 'But for two years, Earth seriously wondered if someone was building around a star.', 'narrow', 'pulse', ''),
    ],
    loopLine: 'You looked at the sky and thought: builders. Remember that feeling. You will need it.',
    caption: 'The star that made scientists say "megastructure". #tabbysstar #space #veyl #shorts',
    pinnedComment: 'If a civilization built around a star, what would they be building FOR?',
    factCheck: 'KIC 8462852 (Boyajian\'s Star) showed irregular ~22% dips; dust is the leading explanation.',
  },

  // ============ PILLAR: ANSWERS (19-23) ============
  {
    id: 19, number: 19, pillar: 'answers', title: 'You Asked If I Am Human', world: 'derelict-station', durationSec: 37,
    hook: 'Earth asked: are you even human under that mask?',
    beats: [
      B(0, 'Earth asked me: are you even human under that mask.', 'neutral', 'none', 'hold up hand as if reading'),
      B(7, 'I remember rain. I remember a door with peeling paint. I remember someone laughing.', 'sad', 'none', 'slow'),
      B(16, 'The suit keeps me alive. The mask keeps me... consistent.', 'narrow', 'static', ''),
      B(24, 'Human is a word for things that live where you live. I do not live there anymore.', 'neutral', 'zoom', ''),
    ],
    loopLine: 'So. Am I human? Ask me again when I find the door with the peeling paint.',
    caption: 'Answering Earth\'s most-asked question. #veyl #lore #space #shorts',
    pinnedComment: 'Next question I answer gets picked from these comments. Choose carefully.',
    factCheck: 'fiction: lore',
  },
  {
    id: 20, number: 20, pillar: 'answers', title: 'What I Eat Out Here', world: 'red-planet', durationSec: 34,
    hook: 'You asked what I eat out here. You will regret asking.',
    beats: [
      B(0, 'You asked what I eat out here. You will regret asking.', 'smirk', 'none', ''),
      B(6, 'The suit recycles everything. And I mean everything. Water. Heat. Breath.', 'neutral', 'none', ''),
      B(13, 'Food is a paste the suit grows from algae and printed protein. It tastes like patience.', 'narrow', 'zoom', 'deadpan'),
      B(22, 'Astronauts on your station drink recycled water too. Yesterday\'s coffee is tomorrow\'s coffee.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'What I would give for one real meal. Ask me what meal, and I will tell you a story.',
    caption: 'The glamorous cuisine of deep space. #astronautfood #space #veyl #shorts',
    pinnedComment: 'What Earth meal should I be homesick for? Best answer becomes canon.',
    factCheck: 'ISS recycles ~90%+ of water including urine and sweat; algae/printed protein are researched space foods.',
  },
  {
    id: 21, number: 21, pillar: 'answers', title: 'Can I See Earth From There?', world: 'asteroid-earth', durationSec: 36,
    hook: 'You asked if I can see Earth from here. Look.',
    beats: [
      B(0, 'You asked if I can see Earth from here. Look.', 'neutral', 'none', 'gesture behind'),
      B(6, 'That blue point. That is everyone you have ever met. Every war. Every song.', 'sad', 'zoom', 'slow pan feel'),
      B(15, 'Your own Voyager took this kind of photo in 1990. The pale blue dot.', 'neutral', 'none', ''),
      B(23, 'A scientist named Sagan said it best. Every saint and sinner lives on a mote of dust.', 'neutral', 'none', ''),
    ],
    loopLine: 'Yes. I can see Earth from here. The question is why I keep looking.',
    caption: 'The view of home from very, very far away. #palebluedot #earth #veyl #shorts',
    pinnedComment: 'If Earth is a single pixel, what is the caption of that photo?',
    factCheck: 'Voyager 1\'s Pale Blue Dot photo (Feb 14, 1990) taken from ~6 billion km; Sagan\'s reflection, 1994.',
  },
  {
    id: 22, number: 22, pillar: 'answers', title: 'Why Don\'t You Just Come Home?', world: 'nebula-drift', durationSec: 38,
    hook: 'You keep asking why I do not just come home.',
    beats: [
      B(0, 'You keep asking why I do not just come home.', 'neutral', 'none', ''),
      B(6, 'Distance is not the problem. Four light-years is a long walk. But I have time.', 'scan', 'none', ''),
      B(14, 'The problem is what followed me out here. It knows my heading. It reads my wake.', 'narrow', 'static', 'lower voice'),
      B(23, 'If I point myself at Earth, I draw it a map.', 'anger', 'glitch', ''),
    ],
    loopLine: 'I stay lost so that you stay found. Do not ask me this again. Please.',
    caption: 'The real reason there is no return trip. #veyl #lore #space #shorts',
    pinnedComment: 'Lore question: what do you think reads a ship\'s wake? Theories below.',
    factCheck: 'fiction: lore',
  },
  {
    id: 23, number: 23, pillar: 'answers', title: 'The Scariest Thing I Have Seen', world: 'dying-star', durationSec: 39,
    hook: 'You asked for the scariest thing I have seen. Fine.',
    beats: [
      B(0, 'You asked for the scariest thing I have seen. Fine.', 'neutral', 'none', ''),
      B(6, 'Not the black holes. They are honest. They tell you exactly what they will do.', 'scan', 'none', ''),
      B(14, 'It was a region of space with nothing in it. No dust. No signal. No background hum.', 'narrow', 'zoom', ''),
      B(23, 'Everything in the universe leaves a fingerprint. This place had been wiped.', 'shock', 'static', ''),
      B(31, 'Something cleaned it.', 'anger', 'glitch', 'whisper'),
    ],
    loopLine: 'I marked the coordinates. Transmission twenty-six is about what was watching from inside it.',
    caption: 'The scariest thing in space is a clean spot. #spacehorror #veyl #shorts #lore',
    pinnedComment: 'What could erase every trace of matter from a region of space? I need theories. Seriously.',
    factCheck: 'fiction: lore (real cosmic voids exist, e.g. Boötes Void, but contain sparse galaxies)',
  },

  // ============ PILLAR: LORE (24-27) ============
  {
    id: 24, number: 24, pillar: 'lore', title: 'The Day I Left Earth', world: 'derelict-station', durationSec: 42,
    hook: 'I never told you how I left. Today the signal is strong enough.',
    beats: [
      B(0, 'I never told you how I left. Today the signal is strong enough.', 'neutral', 'none', ''),
      B(7, 'There was a program. Not one you have read about. Forty of us. One-way tickets.', 'scan', 'none', ''),
      B(15, 'They wove the suits from something they found. Something that was already... webbed.', 'narrow', 'static', 'touch the circuit lines'),
      B(24, 'Launch day, thirty-nine suits went silent on the pad. Mine did not.', 'shock', 'glitch', ''),
      B(33, 'I did not volunteer to be the one who lived. The suit chose.', 'sad', 'zoom', ''),
    ],
    loopLine: 'Why me? The answer is stitched into these red lines. Transmission twenty-seven. Count the threads.',
    caption: 'LORE DROP 001 — the launch. #veyl #lore #cosmicweaver #shorts',
    pinnedComment: 'Thirty-nine suits went dark. First theory to explain why gets woven into the story.',
    factCheck: 'fiction: lore',
  },
  {
    id: 25, number: 25, pillar: 'lore', title: 'What The Weave Actually Is', world: 'nebula-drift', durationSec: 41,
    hook: 'You keep asking about the red lines on the suit. Listen once.',
    beats: [
      B(0, 'You keep asking about the red lines on the suit. Listen once.', 'neutral', 'none', ''),
      B(7, 'They are not decoration. They are not circuitry. They are older than both.', 'scan', 'none', ''),
      B(15, 'There is a structure between stars. Threads of gravity and memory. The Weave.', 'narrow', 'pulse', 'trace a line with finger'),
      B(24, 'Your scientists glimpse it and call it the cosmic web. Filaments of galaxies. They are close.', 'neutral', 'zoom', ''),
      B(32, 'The suit does not glow. It resonates.', 'surge', 'flare', ''),
    ],
    loopLine: 'And lately... something else has been plucking the threads. Transmission twenty-eight hears it too.',
    caption: 'LORE DROP 002 — the Weave. #veyl #lore #cosmicweb #shorts',
    pinnedComment: 'The cosmic web is real, Earth. Look it up. Then ask yourself what walks on it.',
    factCheck: 'fiction: lore (the cosmic web of galaxy filaments is a real large-scale structure)',
  },
  {
    id: 26, number: 26, pillar: 'lore', title: 'The Thing That Follows Me', world: 'dying-star', durationSec: 43,
    hook: 'It is closer tonight. So I am going to say this quickly.',
    beats: [
      B(0, 'It is closer tonight. So I am going to say this quickly.', 'narrow', 'static', 'urgent but controlled'),
      B(6, 'It does not move through space. It moves through absence. Clean spots. Wiped regions.', 'scan', 'glitch', ''),
      B(15, 'I told you about the erased place in transmission twenty-three. I lied about one detail.', 'neutral', 'zoom', ''),
      B(24, 'It was not empty when I found it. It was empty when I left.', 'shock', 'shake', 'pause. let it land'),
      B(34, 'The suit will not say its name. The threads go quiet when I ask.', 'sad', 'static', ''),
    ],
    loopLine: 'If my transmissions ever stop mid-sentence... do not look for me. Look up.',
    caption: 'LORE DROP 003 — the Follower. #veyl #lore #spacehorror #shorts',
    pinnedComment: 'It erases everything it touches. Except me. Why? Wrong answers might be right.',
    factCheck: 'fiction: lore',
  },
  {
    id: 27, number: 27, pillar: 'lore', title: 'I Was Not The Only Survivor', world: 'derelict-station', durationSec: 42,
    hook: 'I found this station three cycles ago. The airlock was already open.',
    beats: [
      B(0, 'I found this station three cycles ago. The airlock was already open.', 'neutral', 'none', ''),
      B(7, 'No bodies. No logs. But in the dust on the console, someone had written numbers.', 'scan', 'zoom', ''),
      B(15, 'Suit thirty-one. One of the thirty-nine that went silent on the launch pad.', 'shock', 'static', ''),
      B(24, 'Except it did not go silent, did it. It went somewhere.', 'narrow', 'glitch', ''),
      B(31, 'The dust was fresh. The station is abandoned. Both of those are true.', 'anger', 'shake', ''),
    ],
    loopLine: 'Suit thirty-one, if you are receiving this... you know which thread to pull. I am listening.',
    caption: 'LORE DROP 004 — Suit 31. #veyl #lore #cosmicweaver #shorts',
    pinnedComment: 'Suit 31 is out there. Should I trust them? The comments decide what I do next.',
    factCheck: 'fiction: lore',
  },

  // ============ PILLAR: TREND (28-30) ============
  {
    id: 28, number: 28, pillar: 'trend', title: 'POV: Your Last Transmission Home', world: 'red-planet', durationSec: 35,
    hook: 'POV. You get one final message to Earth. Thirty seconds.',
    beats: [
      B(0, 'POV. You get one final message to Earth. Thirty seconds. Signal is dying.', 'neutral', 'static', 'trend format: countdown energy'),
      B(8, 'You do not talk about science. You do not talk about the mission.', 'sad', 'none', ''),
      B(15, 'You say: the window in the kitchen. Leave it open in summer. The cat likes it.', 'neutral', 'zoom', 'small human details'),
      B(24, 'That is what thirty seconds is for. The small things are the big things.', 'sad', 'pulse', ''),
    ],
    loopLine: 'Signal restored. This time. What would YOUR thirty seconds say? Go.',
    caption: 'POV: your last 30 seconds of signal. #pov #space #veyl #shorts',
    pinnedComment: 'Your final 30-second message — write it below. I will read the best on air.',
    factCheck: 'fiction: format piece',
  },
  {
    id: 29, number: 29, pillar: 'trend', title: 'Things That Only Make Sense In Space', world: 'nebula-drift', durationSec: 36,
    hook: 'Things that only make sense out here. Number one.',
    beats: [
      B(0, 'Things that only make sense out here. Number one.', 'smirk', 'none', 'fast list energy'),
      B(5, 'Crying is dangerous. Tears do not fall. They pool on your eyes like glass.', 'neutral', 'zoom', ''),
      B(13, 'Number two. You grow taller. Your spine stretches five centimeters without gravity.', 'scan', 'pulse', ''),
      B(21, 'Number three. A sunrise every ninety minutes. Sixteen a day. You stop counting.', 'neutral', 'flare', ''),
      B(28, 'Number four. Silence so complete you hear your own heartbeat as a stranger.', 'narrow', 'static', ''),
    ],
    loopLine: 'Number five does not translate. You would have to come out here. Do not come out here.',
    caption: 'Space facts that feel illegal. #spacefacts #veyl #shorts #listicle',
    pinnedComment: 'Which one broke your brain? Number five is classified. For now.',
    factCheck: 'Tears pool in microgravity; astronauts gain ~3-5cm height; ISS sees ~16 sunrises daily.',
  },
  {
    id: 30, number: 30, pillar: 'trend', title: 'Rating Your Solar System\'s Planets', world: 'asteroid-earth', durationSec: 40,
    hook: 'I passed through your solar system once. Rating the planets.',
    beats: [
      B(0, 'I passed through your solar system once. Rating the planets. Honestly.', 'smirk', 'none', 'fun energy, still deadpan'),
      B(6, 'Mercury. A cannonball with anxiety. Four out of ten.', 'neutral', 'zoom', ''),
      B(12, 'Venus. Nine hundred degrees. Acid rain. Beautiful liar. Seven out of ten.', 'narrow', 'pulse', ''),
      B(19, 'Jupiter. Carries your asteroid strikes so you do not have to. Protective older brother. Nine.', 'scan', 'flare', ''),
      B(27, 'Saturn. Rings made of ice and dead moons. Unnecessary. Flawless. Ten.', 'shock', 'none', ''),
      B(33, 'Earth. Loud. Fragile. Growing on me. No rating.', 'sad', 'zoom', 'soften'),
    ],
    loopLine: 'I do not rate the things I am still trying to get back to. Replay that.',
    caption: 'A deep space traveler rates your planets. #planets #rating #veyl #shorts',
    pinnedComment: 'Rate YOUR favorite planet in the comments. Defend it. I am watching.',
    factCheck: 'Venus surface ~465°C with sulfuric acid clouds; Jupiter deflects/absorbs many impactors; Saturn\'s rings are mostly water ice.',
  },
];

/* ============ THE LAUNCH SEQUENCE — the first five uploads ============
   Retention physics baked into every one:
   - Hook lands inside 1.5 seconds. No name, no intro, no logo. Cold open.
   - 22-30 seconds total: short enough to loop, long enough to pay off.
   - Every script ends by pointing back at its own first line (the loop),
     because rewatches are the single strongest Shorts ranking signal.
   - One idea per video. Personal stakes ("you", "your sun", "your skin").
   - The comment bait is a genuine question, not "like and subscribe".
   - `mood` drives the locked studio voice's prosody server-side.
   Publish order = the order below. One every 48 hours. Same time of day. */
export const LAUNCH_SEQUENCE = [
  {
    id: 31, number: 31, pillar: 'launch', publishOrder: 1, best: true,
    title: 'LAUNCH 1 · The Sun Is Already Gone', world: 'asteroid-earth', durationSec: 27, mood: 'mystery',
    hook: 'If your sun died right now — you would not know.',
    beats: [
      B(0, 'If your sun died right now — you would not know.', 'neutral', 'none', 'dead still, quiet menace'),
      B(4, 'Light takes eight minutes and twenty seconds to cross the distance. Nothing warns you faster.', 'scan', 'none', 'slow head turn to Earth'),
      B(12, 'So for eight whole minutes, you would keep living in a world that was already over.', 'narrow', 'zoom', 'punch in, let it land'),
      B(19, 'That warmth on your skin right now? That is history. Touching you.', 'sad', 'pulse', 'soften, look down'),
    ],
    loopLine: 'Go check the sky. Still there? ...As of eight minutes ago.',
    videoTitle: 'If The Sun Died Right Now, You Wouldn\u2019t Know',
    description: 'Light takes 8 minutes and 20 seconds to reach Earth. Which means the sun you see is never the sun that is. A transmission from somewhere past your sky.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['space', 'space facts', 'the sun', 'speed of light', 'astronomy', 'science shorts', 'mind blowing facts', 'universe', 'shorts', 'scifi character'],
    caption: 'You are always 8 minutes behind your own star. #space #sun #shorts #spacefacts',
    pinnedComment: 'Honest question, Earth: if you had 8 minutes left, would you even want to know?',
    factCheck: 'Sunlight travel time ~8 min 20 s (1 AU / c). No signal, gravitational or light, propagates faster than c.',
    whyItWorks: 'Zero prior knowledge needed, personal stakes in sentence one, and the loop line physically sends viewers to look at the sky and rewatch. Highest floor, highest ceiling — this is upload #1.',
  },
  {
    id: 32, number: 32, pillar: 'launch', publishOrder: 2,
    title: 'LAUNCH 2 · You Are Faster Than A Bullet', world: 'nebula-drift', durationSec: 26, mood: 'urgent',
    hook: 'Right now, you are moving faster than a bullet.',
    beats: [
      B(0, 'Right now, you are moving faster than a bullet.', 'neutral', 'none', 'lean in fast, dead serious'),
      B(4, 'You think you are sitting still. You are not. The ground is spinning.', 'scan', 'zoom', 'point down'),
      B(9, 'Earth is racing around the sun. Thirty times faster than a bullet.', 'neutral', 'pulse', ''),
      B(14, 'And the sun is falling through the galaxy. Dragging you with it.', 'surge', 'shake', 'energy rising'),
      B(19, 'Since this video started? You just moved ten thousand kilometers.', 'shock', 'flare', 'hit the number, pause'),
    ],
    loopLine: 'And you felt nothing. Watch it again. You will move ten thousand more.',
    videoTitle: 'You Are Moving Faster Than A Bullet Right Now',
    description: 'You have never sat still in your life. Earth spins, orbits, and falls through the galaxy at over 500 kilometers every second \u2014 and you feel none of it. A transmission from somewhere past your sky.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['space', 'earth rotation', 'galaxy', 'milky way', 'space facts', 'physics', 'mind blowing facts', 'science shorts', 'universe', 'shorts'],
    caption: 'You just moved 10,000 km watching this. #space #physics #shorts',
    pinnedComment: 'You moved 10,000 km during this video. Where do you wish it took you?',
    factCheck: 'Rifle bullet ~1 km/s; Earth orbits at ~30 km/s; total motion vs cosmic background ~550 km/s \u2192 ~11,000 km in 20 seconds.',
    whyItWorks: 'One relatable anchor (a bullet) replaces three abstract numbers \u2014 the brain can feel it. The final beat makes the fact happen TO the viewer during the video, and the loop line turns a rewatch into a physical event.',
  },
  {
    id: 33, number: 33, pillar: 'launch', publishOrder: 3,
    title: 'LAUNCH 3 · The Prettiest Planet Wants You Dead', world: 'derelict-station', durationSec: 28, mood: 'mystery',
    hook: 'The prettiest planet in space wants you dead.',
    beats: [
      B(0, 'The prettiest planet in space wants you dead.', 'neutral', 'none', 'calm, almost fond'),
      B(4, 'From far away, it looks like one calm blue ocean. Bluer than Earth.', 'scan', 'zoom', 'looking at a memory'),
      B(10, 'But there is no water there. None. That blue... is glass.', 'narrow', 'static', 'tone turns'),
      B(17, 'Melted glass, blown by wind seven times faster than sound. It never falls.', 'shock', 'shake', ''),
      B(24, 'It rains sideways.', 'anger', 'glitch', 'flat. cold. stop.'),
    ],
    loopLine: 'Now look at that pretty blue again. Still want to visit?',
    videoTitle: 'The Prettiest Planet In Space Rains Glass \u2014 Sideways',
    description: 'It looks like a calm blue marble. The blue is melted glass, and the wind is 7x the speed of sound \u2014 so the glass rains sideways. A transmission from somewhere past your sky.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['exoplanet', 'hd 189733b', 'space', 'space facts', 'planets', 'astronomy', 'scary space', 'science shorts', 'universe', 'shorts'],
    caption: 'The prettiest planet in space rains glass. Sideways. #exoplanet #space #shorts',
    pinnedComment: 'Ten seconds on its surface, fully protected, one look at the sky. Do you go?',
    factCheck: 'HD 189733b: cobalt-blue color from silicate (glass) clouds; ~8,700 km/h winds; ~930\u00b0C (Hubble/ESA).',
    whyItWorks: 'Beauty-to-horror inversion stated in six words a child understands. The catalog number is gone \u2014 names nobody can say cost retention. "It rains sideways." stays as the quotable spike, and the loop line dares the viewer to scrub back to the pretty blue.',
  },
  {
    id: 34, number: 34, pillar: 'launch', publishOrder: 4,
    title: 'LAUNCH 4 · Something Called Earth. Once.', world: 'derelict-station', durationSec: 30, mood: 'mystery',
    hook: 'In 1977, something called Earth. Nobody knows who.',
    beats: [
      B(0, 'In 1977, something called Earth. Nobody knows who.', 'neutral', 'none', 'whisper energy, dead still'),
      B(5, 'A telescope in Ohio heard it. Seventy-two seconds. Louder than anything in the sky.', 'scan', 'none', ''),
      B(12, 'The scientist on duty circled it in red ink. He wrote one word. Wow.', 'neutral', 'zoom', ''),
      B(19, 'They pointed everything at that spot. For forty years. Silence.', 'sad', 'static', 'let the silence sit'),
      B(25, 'I have heard that sound out here. Twice.', 'narrow', 'glitch', 'cold. hold the lens.'),
    ],
    loopLine: 'The second time... is the next video. Follow the signal. You do not want to miss it.',
    videoTitle: 'Something Called Earth In 1977. It Never Called Back.',
    description: 'The Wow! signal: 72 seconds, louder than anything in the sky, never repeated, never explained. I know that sound. A transmission from somewhere past your sky.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['wow signal', 'seti', 'aliens', 'space mystery', 'unexplained', 'space facts', 'radio signal', 'science shorts', 'universe', 'shorts'],
    caption: 'It called once in 1977. Then silence. #wowsignal #space #mystery #shorts',
    pinnedComment: 'Who do YOU think called? Top theory gets answered in a future transmission.',
    factCheck: 'Wow! signal: Aug 15 1977, Big Ear telescope, 72 s, ~30\u03c3 above background at 1420 MHz; never re-detected.',
    whyItWorks: '"Something called Earth" is a phone-call metaphor \u2014 instantly human, zero jargon. Every beat is under twelve words. The final beat plus the loop line turn a true fact into a serialized cliffhanger with a named payoff: the next video. This is the subscriber-converter.',
  },
  {
    id: 35, number: 35, pillar: 'launch', publishOrder: 5,
    title: 'LAUNCH 5 · A Piece Of The Universe Is Missing', world: 'nebula-drift', durationSec: 29, mood: 'somber',
    hook: 'There is a hole in the universe. I have seen its edge.',
    beats: [
      B(0, 'There is a hole in the universe. I have seen its edge.', 'neutral', 'none', 'slow, heavy'),
      B(5, 'A patch of space so big, light needs three hundred million years to cross it.', 'scan', 'zoom', ''),
      B(12, 'It should be packed with ten thousand galaxies. Count them. There are sixty.', 'narrow', 'none', 'let the math land'),
      B(19, 'If you lived inside it, your night sky would be black. Empty. Nothing.', 'sad', 'static', ''),
      B(25, 'You would swear you were alone. Maybe something in there still does.', 'shock', 'pulse', 'quiet horror'),
    ],
    loopLine: 'The universe does not make mistakes this big. So what made this one? Look again.',
    videoTitle: 'The Hole In The Universe Nobody Can Explain',
    description: 'A patch of space that should hold 10,000 galaxies. It holds 60. Nobody knows why. A transmission from somewhere past your sky.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['bootes void', 'space', 'void', 'space mystery', 'galaxies', 'dark matter', 'space facts', 'science shorts', 'universe', 'shorts'],
    caption: '10,000 galaxies should be there. 60 are. #space #mystery #shorts',
    pinnedComment: 'What is in the hole? I have flown its edge. I will confirm or deny the top answer.',
    factCheck: 'Bo\u00f6tes Void ~330 Mly diameter, ~60 known galaxies vs ~2,000+ expected for its volume (discovered 1981).',
    whyItWorks: 'The name "Bo\u00f6tes" is gone from the spoken script \u2014 unpronounceable words break immersion. "10,000 vs 60" is the whole video in two numbers anyone can hold. The loop line replaces a vague musing with a direct question plus a rewatch command.',
  },
];

/* the launch sequence leads the log — record these five first, in order */
TRANSMISSIONS.unshift(...LAUNCH_SEQUENCE);

/* Channel identity — handle candidates, strongest first. All checked for
   spellability (say it once, type it right), search collision (nothing big
   owns it), and merch/series headroom. */
export const CHANNEL_KIT = {
  handles: ['@FollowTheSignal', '@TheCosmicWeaver', '@VEYLtransmits', '@SignalFromVEYL', '@PastYourSky'],
  tagline: 'Transmissions from somewhere past your sky.',
  uploadCadence: 'One Short every 48 hours, same hour every time. Never miss.',
  descriptionFooter: '\n\nNew signal every 48 hours. Follow the signal.',
};

export const EMOTE_TO_EXPR = {
  neutral: 'calm', smirk: 'smirk', anger: 'fury', sad: 'narrow',
  scan: 'calm', surge: 'shock', glitch: 'fury',
};
