/* SpaceSpidey shooting-script library.
   Channel: SpaceSpidey — transmissions from somewhere past your sky.
   Character: SpaceSpidey, the last survivor of a suit woven from the cosmic web.
   35 scripts: 5 launch uploads + 30 across 5 content pillars.

   Every script in this file is built on the same retention physics (see
   VIRAL_RULES). Scripts are authored in FINAL form — there is no rewrite layer
   patching lines at runtime any more, so what you read here is what gets
   teleprompted, voiced and captioned. */

export const CHANNEL = {
  name: 'SpaceSpidey',
  spoken: 'SpaceSpidey',
  tagline: 'Transmissions from somewhere past your sky.',
};

/* ============================ THE RULES ============================
   Why the first five uploads underperformed, and what every script below
   now does differently. These are the levers that actually move Shorts:
   watch-time ratio (>100% = loops), swipe-away rate in the first 2 seconds,
   comment velocity in the first hour, and re-watch. Nothing else. */
export const VIRAL_RULES = [
  { rule: 'Hook is 8 words or fewer and lands before 1.5s', why: 'The swipe decision happens in under two seconds. A hook that needs a run-up is already lost.' },
  { rule: 'No name, no logo, no "welcome back", no intro', why: 'Any second spent on identity is a second not spent earning the scroll-stop. Identity is carried by the suit and the voice.' },
  { rule: 'Second person in the first sentence', why: '"You" makes the fact a personal threat or gift. "Space is big" loses; "you are already moving" wins.' },
  { rule: 'One idea per video, one feelable number', why: 'Comparisons beat units. "Four billion tons" is noise; "every human squeezed into a sugar cube" is a picture.' },
  { rule: 'A new reveal every 3-5 seconds, each beat under 14 words', why: 'Each reveal resets the attention timer. Long sentences are where the retention graph falls off a cliff.' },
  { rule: 'Emotional turn at roughly 65% of the runtime', why: 'A fact gets a view. A fact that turns into dread, awe or grief gets a share.' },
  { rule: 'Pay the promise off. Never bait without delivery', why: 'Unpaid hooks produce the exact pattern of high views with no likes: people watched, felt cheated, left nothing.' },
  { rule: 'Total runtime 22-32 seconds', why: 'Short enough to loop before the viewer decides to leave, long enough to complete a story. Loops push watch time over 100%.' },
  { rule: 'The last line points back into the first line', why: 'A seamless loop is the single cheapest way to double watch time, and re-watch is the strongest ranking signal on Shorts.' },
  { rule: 'Pinned comment is a real question with a binary or a dare', why: 'Open-ended prompts get read; binary prompts get answered. Comment velocity in hour one decides the reach ceiling.' },
  { rule: 'No unpronounceable proper nouns in spoken lines', why: 'A word the viewer cannot say breaks immersion and kills the share ("you have to see this" requires a sayable subject). Keep catalog names in the description.' },
  { rule: 'Never say like, comment, or subscribe', why: 'It reads as a toll gate. Earn it with the loop and the question instead — the ask converts worse than the cliffhanger.' },
];

export const PILLARS = {
  launch: { label: 'LAUNCH', color: '#FF2E63', description: 'The first five uploads. Retention-engineered, loop-first, upload kit included.', cadence: 'day 1-9, one every 48h' },
  transmission: { label: 'TRANSMISSION', color: '#00FFFF', description: 'A mind-blowing space fact, witnessed first-person from out there.', cadence: '3x per week' },
  mystery: { label: 'MYSTERY', color: '#FFB000', description: 'Unsolved cosmic questions told by someone living inside them.', cadence: '2x per week' },
  answers: { label: 'ANSWERS', color: '#00FF41', description: 'SpaceSpidey replies to Earth comments, always in character.', cadence: '1-2x per week' },
  lore: { label: 'LORE DROP', color: '#FF1A1A', description: 'Who SpaceSpidey is, and what spun the suit. Cliffhangers only.', cadence: '1 per 8-10 videos' },
  trend: { label: 'TREND HIJACK', color: '#B366FF', description: 'Trending formats performed from a nebula. Contrast stops the scroll.', cadence: 'when a trend fits' },
};

/* Hooks that pass the two-second test. Each is a threat, a debt, or a secret
   aimed directly at the viewer — never a description of space. */
export const HOOK_BANK = [
  'The sun could already be dead.',
  'You are moving faster than a bullet.',
  'Something called Earth. Once.',
  'You have never seen the sky. Only its past.',
  'One hour here costs you seven years.',
  'Space is not empty. It is touching you.',
  'A spoon of this outweighs a mountain.',
  'Space has a smell. Astronauts all agree.',
  'A machine you built will outlive your species.',
  'Two hundred billion stars. Nobody is home.',
  'There is a test almost nobody survives.',
  'The universe could end mid-sentence.',
  'Most of everything is invisible.',
  'You freeze forever and fall in seconds.',
  'Something out here keeps perfect time.',
  'A star kept switching itself off.',
  'I found a place that had been wiped clean.',
  'Thirty-nine suits went dark. Mine did not.',
  'Something followed me out of the dark.',
  'Do not look for me. Look up.',
];

/* Title patterns that survive the Shorts feed: a promise in 4-7 words,
   a payoff the thumbnail cannot spoil, zero jargon. */
export const TITLE_FORMULAS = [
  'If {event} Happened Right Now, You Would Not Know',
  'You Are {surprising verb} Right Now',
  'The {superlative} Thing In Space {does something awful}',
  'Something {verb} Earth In {year}. It Never {verb} Back.',
  'The {noun} Nobody Can Explain',
  '{number} vs {number}: The Number That Broke Astronomy',
];

const B = (t, text, emote = 'neutral', fx = 'none', note = '') => ({ t, text, emote, fx, note });

export const TRANSMISSIONS = [
  // ============ PILLAR: TRANSMISSION (1-10) ============
  {
    id: 6, number: 6, pillar: 'transmission', title: 'Your Voice Is Four Years Late', world: 'nebula-drift', durationSec: 28, mood: 'hero',
    firstFrame: 'THIS IS 4 YEARS OLD',
    hook: 'You are hearing a voice that is four years late.',
    beats: [
      B(0, 'You are hearing a voice that is four years late.', 'neutral', 'none', 'dead still, straight into lens'),
      B(5, 'I said these words before you ever found this channel.', 'scan', 'none', 'slow head turn'),
      B(10, 'Nothing out here travels faster than light. Not even a warning.', 'neutral', 'zoom', 'punch in'),
      B(16, 'So I do not know if anyone is still there to hear me.', 'sad', 'none', 'let it land'),
      B(22, 'Say something back. It reaches me in four years.', 'smirk', 'pulse', 'small, dangerous smile'),
    ],
    loopLine: 'And whatever you say, I already answered. Four years ago. Listen again.',
    videoTitle: 'This Message Left Space Four Years Ago',
    description: 'Radio and light cross the nearest star in 4.24 years. Every word of this transmission is older than the moment you are watching it.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['space', 'light years', 'speed of light', 'proxima centauri', 'space facts', 'astronomy', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'Every word of this is four years old. #space #spacefacts #shorts #SpaceSpidey',
    pinnedComment: 'One sentence you would send four years into the dark. Go. I read every one.',
    factCheck: 'Proxima Centauri is ~4.24 light-years away; light and radio take 4.24 years to cross it.',
    whyItWorks: 'The old script opened by introducing a character. This one opens by making the viewer part of the physics — they are already inside the delay. The loop line makes replaying the video the punchline of the joke.',
  },
  {
    id: 7, number: 7, pillar: 'transmission', title: 'A Black Hole Has Been Humming For 2.5 Billion Years', world: 'dying-star', durationSec: 29, mood: 'somber',
    firstFrame: 'IT NEVER STOPS',
    hook: 'Something out here has been screaming one note since before Earth had life.',
    beats: [
      B(0, 'Something has been screaming one note since before Earth had life.', 'neutral', 'none', 'whisper energy'),
      B(6, 'A black hole. Pressing on the gas around it. Over and over.', 'scan', 'none', ''),
      B(11, 'That makes a real sound. One note. B flat.', 'neutral', 'zoom', 'hit the note name'),
      B(16, 'Fifty-seven octaves below the lowest key on a piano.', 'narrow', 'none', ''),
      B(21, 'It started that note two and a half billion years ago. It has not stopped.', 'shock', 'flare', 'pause after'),
    ],
    loopLine: 'It is still holding it. Right now. While you decide whether to watch this again.',
    videoTitle: 'A Black Hole Has Held One Note For 2.5 Billion Years',
    description: 'The black hole in the Perseus cluster generates pressure waves in the surrounding gas — a real note, B-flat, roughly 57 octaves below middle C. It has been sounding for about 2.5 billion years.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['black hole', 'space sounds', 'perseus cluster', 'nasa', 'space facts', 'astronomy', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'One note. 2.5 billion years. Still going. #blackhole #space #shorts #SpaceSpidey',
    pinnedComment: 'Would you listen to it for one hour if it were audible? Yes or no. No middle answers.',
    factCheck: 'Perseus cluster black hole drives pressure waves at B-flat, ~57 octaves below middle C (NASA Chandra, 2003).',
    whyItWorks: 'Replaces the abstract word "hum" with "screaming", puts a timescale the viewer can compare to their own species in beat one, and ends on a present-tense fact that is still happening during the rewatch.',
  },
  {
    id: 8, number: 8, pillar: 'transmission', title: 'You Have Never Seen The Sky', world: 'asteroid-earth', durationSec: 27, mood: 'somber',
    firstFrame: 'THIS SKY IS FAKE',
    hook: 'You have never once seen the real night sky.',
    beats: [
      B(0, 'You have never once seen the real night sky.', 'neutral', 'none', 'flat, certain'),
      B(4, 'Every star you look at is a delayed photograph.', 'scan', 'none', ''),
      B(9, 'Some of that light left before your language existed.', 'neutral', 'zoom', ''),
      B(15, 'A few of those stars died a thousand years ago. They still shine for you.', 'sad', 'none', 'slow down'),
      B(21, 'You are not stargazing. You are watching ghosts.', 'narrow', 'pulse', 'cold, final'),
    ],
    loopLine: 'Go outside tonight and look at the dead. Then come back and hear it again.',
    videoTitle: 'You Have Never Seen The Real Night Sky',
    description: 'Starlight takes years to millennia to arrive, so the sky you see is always a record of the past — including stars that no longer exist.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['night sky', 'stars', 'light years', 'time travel', 'space facts', 'astronomy', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'You are watching ghosts every single night. #space #stars #shorts #SpaceSpidey',
    pinnedComment: 'Does that make you feel small or lucky? Pick one word and post it.',
    factCheck: 'Lookback time: starlight takes years to millennia to arrive; some visible stars have already died.',
    whyItWorks: 'The claim is an accusation, not a fact, so the viewer stays to disprove it. "Watching ghosts" is the quotable line and the caption, and the loop line assigns homework that ends in a rewatch.',
  },
  {
    id: 9, number: 9, pillar: 'transmission', title: 'Your Sun Is Invisible From Here', world: 'nebula-drift', durationSec: 27, mood: 'somber',
    firstFrame: 'I CANNOT FIND YOUR SUN',
    hook: 'I looked for your sun tonight. I could not find it.',
    beats: [
      B(0, 'I looked for your sun tonight. I could not find it.', 'neutral', 'none', 'searching the sky'),
      B(5, 'From out here it is not a sun. It is a dust speck.', 'scan', 'none', ''),
      B(10, 'Two hundred billion other stars sit on top of it.', 'neutral', 'zoom', ''),
      B(16, 'Everyone you love lives beside a light nobody out here can pick out.', 'sad', 'none', 'let it land'),
      B(22, 'That is not sadness. That is camouflage.', 'smirk', 'glitch', 'sharp tone flip'),
    ],
    loopLine: 'Being impossible to find may be the only reason Earth is still there. Look again.',
    videoTitle: 'Your Sun Is Invisible From Deep Space',
    description: 'The Sun is an ordinary G-type star. Move far enough away and it disappears into the crowd entirely.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['the sun', 'milky way', 'stars', 'space facts', 'astronomy', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'Your sun is a dust speck from out here. #sun #space #shorts #SpaceSpidey',
    pinnedComment: 'Camouflage or prison? One word. I am counting the votes.',
    factCheck: 'The Sun is a G-type main sequence star, invisible to the unaided eye beyond roughly 60 light-years.',
    whyItWorks: 'The turn at 22 seconds flips a depressing fact into a survival instinct, which is what makes it shareable rather than just sad. The pinned comment is a two-option vote, the fastest kind of comment to leave.',
  },
  {
    id: 10, number: 10, pillar: 'transmission', title: 'One Hour Here Costs Seven Years There', world: 'dying-star', durationSec: 30, mood: 'urgent',
    firstFrame: '1 HOUR = 7 YEARS',
    hook: 'One hour where I am standing costs you seven years.',
    beats: [
      B(0, 'One hour where I am standing costs you seven years.', 'neutral', 'none', ''),
      B(5, 'Near enormous gravity, clocks genuinely run slower. Measured. Not theory.', 'scan', 'none', ''),
      B(11, 'Eat lunch beside a black hole. Come home. Everyone is seven years older.', 'shock', 'zoom', 'hit the image'),
      B(18, 'Your phone already proves it. Satellite clocks drift every single day.', 'neutral', 'none', ''),
      B(24, 'They get corrected every night, or your maps would put you in the sea.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'So compared to me, how old are you actually? Do the math again.',
    videoTitle: 'One Hour In Space Can Cost You Seven Years',
    description: 'Gravitational time dilation is measured, not hypothetical: GPS satellite clocks are corrected by about 38 microseconds a day or navigation drifts kilometres off.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['time dilation', 'relativity', 'black hole', 'interstellar', 'gps', 'space facts', 'physics', 'science shorts', 'universe', 'shorts'],
    caption: 'Lunch out here costs you seven years. #timedilation #space #shorts #SpaceSpidey',
    pinnedComment: 'One hour with me, seven years gone at home. Do you get in the ship? Yes or no.',
    factCheck: 'Gravitational and kinematic time dilation; GPS satellite clocks are corrected by ~38 microseconds/day.',
    whyItWorks: 'The GPS beat is the credibility spike — it converts a movie idea into something in the viewer\'s pocket, which is what stops the "this is fake" comments that kill a video\'s like ratio.',
  },
  {
    id: 11, number: 11, pillar: 'transmission', title: 'Space Is Touching You Right Now', world: 'nebula-drift', durationSec: 28, mood: 'urgent',
    firstFrame: 'IT IS TOUCHING YOU',
    hook: 'Something from the sun is touching you right now.',
    beats: [
      B(0, 'Something from the sun is touching you right now.', 'neutral', 'none', ''),
      B(5, 'The sun does not just shine. It throws pieces of itself outward.', 'scan', 'none', 'gesture wide'),
      B(11, 'A wind of shredded star, moving a million miles an hour.', 'surge', 'shake', 'energy up'),
      B(17, 'It is why comets have tails. It is why the poles glow.', 'neutral', 'none', ''),
      B(22, 'The void is not empty. It is an ocean, and it has a current.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'And something in that current just pushed back at me. Play it again.',
    videoTitle: 'The Sun Is Touching You Right Now',
    description: 'Solar wind streams outward at 300-800 km/s, shaping comet tails and lighting the aurora. Interplanetary space is plasma, dust and magnetic field — not nothing.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['solar wind', 'aurora', 'the sun', 'space weather', 'space facts', 'astronomy', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'The "vacuum" of space is an ocean with a current. #solarwind #space #shorts',
    pinnedComment: 'If space is an ocean, what is swimming in it? Best answer becomes canon on this channel.',
    factCheck: 'Solar wind travels at ~300-800 km/s (roughly 0.7-1.8 million mph); it shapes comet tails and drives aurorae.',
    whyItWorks: 'Proximity beats scale. "It is touching you" outperforms every version of "space is huge", and the aurora beat gives the fact a receipt the viewer has already seen photos of.',
  },
  {
    id: 12, number: 12, pillar: 'transmission', title: 'Sunsets Are Blue On Mars', world: 'red-planet', durationSec: 26, mood: 'somber',
    firstFrame: 'BLUE SUNSET',
    hook: 'I watched a sunset today. It was blue.',
    beats: [
      B(0, 'I watched a sunset today. It was blue.', 'neutral', 'none', 'calm, seated energy'),
      B(4, 'On Mars, the sky is rust all day long.', 'scan', 'none', ''),
      B(9, 'Then the sun drops, and the dust bends the light backwards.', 'neutral', 'zoom', ''),
      B(15, 'Red sky. Blue sunset. Exactly opposite to yours.', 'narrow', 'none', ''),
      B(20, 'Same star. Same light. A completely different goodbye.', 'sad', 'pulse', 'long pause'),
    ],
    loopLine: 'Red goodbye or blue one. Which planet do you want to say it on?',
    videoTitle: 'Sunsets Are Blue On Mars. Really.',
    description: 'Fine Martian dust scatters red light forward and lets blue linger near the Sun, so the daytime sky is butterscotch and the sunset is blue — confirmed in NASA rover images.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['mars', 'blue sunset', 'nasa rover', 'perseverance', 'space facts', 'astronomy', 'science shorts', 'planets', 'shorts', 'spacespidey'],
    caption: 'Mars sunsets are blue. NASA has the photos. #mars #sunset #space #shorts',
    pinnedComment: 'Blue sunset every night, but you never come back. Do you take it?',
    factCheck: 'Mars sunsets appear blue: fine dust scatters red light and permits blue near the Sun (NASA rover imagery).',
    whyItWorks: 'The shortest script in the pillar and the most rewatched kind: pure visual payoff with a symmetry the brain enjoys completing. The dare in the pinned comment supplies the conflict the fact itself lacks.',
  },
  {
    id: 13, number: 13, pillar: 'transmission', title: 'A Spoon Of This Weighs More Than A Mountain', world: 'dying-star', durationSec: 29, mood: 'urgent',
    firstFrame: 'ONE SPOON',
    hook: 'One spoon of this would weigh more than a mountain.',
    beats: [
      B(0, 'One spoon of this would weigh more than a mountain.', 'neutral', 'none', ''),
      B(5, 'When a giant star dies, it crushes itself into a ball the size of a city.', 'scan', 'none', ''),
      B(11, 'Everything a whole star had. Packed into something you could drive across.', 'neutral', 'zoom', ''),
      B(17, 'One spoonful of it weighs about as much as every human alive.', 'shock', 'flare', 'hit the comparison'),
      B(23, 'And some of them spin seven hundred times a second while weighing that.', 'surge', 'shake', ''),
    ],
    loopLine: 'A city-sized star spinning faster than a drill. Watch that again slowly.',
    videoTitle: 'One Spoon Of This Star Outweighs A Mountain',
    description: 'Neutron star matter reaches around 10^17 kg per cubic metre. Millisecond pulsars spin over 700 times a second while holding that density.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['neutron star', 'pulsar', 'space facts', 'astronomy', 'physics', 'science shorts', 'universe', 'stars', 'shorts', 'spacespidey'],
    caption: 'One spoon = the mass of humanity. #neutronstar #space #shorts #SpaceSpidey',
    pinnedComment: 'Heaviest thing you can picture? Post it. The universe beats it every time.',
    factCheck: 'Neutron star density ~10^17 kg/m^3; fastest known pulsars spin 700+ times per second.',
    whyItWorks: 'Swaps "four billion tons" for "every human alive" — a number nobody feels, replaced by a picture everybody sees. The spin beat is the second climax, which stops the drop-off that usually follows the main reveal.',
  },
  {
    id: 14, number: 14, pillar: 'transmission', title: 'Space Has A Smell', world: 'derelict-station', durationSec: 28, mood: 'hero',
    firstFrame: 'IT SMELLS LIKE THIS',
    hook: 'Space has a smell, and every astronaut describes it the same way.',
    beats: [
      B(0, 'Space has a smell. Every astronaut describes it the same way.', 'neutral', 'none', ''),
      B(6, 'Burnt steak. Hot metal. Gunpowder.', 'scan', 'none', 'three sharp beats'),
      B(11, 'Not outside. On the suit, the moment they come back in.', 'neutral', 'zoom', ''),
      B(18, 'Space is slowly burning the fabric. Like rust burns iron, but faster.', 'narrow', 'static', ''),
      B(24, 'The universe smells like something burning, because it is.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'This station smells like it too. Nothing here has burned. Yet.',
    videoTitle: 'Space Smells Like Burnt Metal. Here Is Why.',
    description: 'Astronauts consistently report a seared, metallic, gunpowder odour clinging to suits and airlocks after a spacewalk — atomic oxygen reacting with suit surfaces.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['astronaut', 'iss', 'space smell', 'spacewalk', 'space facts', 'nasa', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'Astronauts all say space smells the same. #astronaut #space #shorts #SpaceSpidey',
    pinnedComment: 'What do you think a dead star smells like? I will tell you who got closest.',
    factCheck: 'Astronauts report a burnt/metallic odour on suits after EVAs, attributed to atomic oxygen reactions.',
    whyItWorks: 'Smell is the least-used sense in space content, so the premise itself is the pattern interrupt. The loop line converts a science fact into a horror cliffhanger at zero cost.',
  },
  {
    id: 15, number: 15, pillar: 'transmission', title: 'The Machine That Outlives Everyone', world: 'asteroid-earth', durationSec: 30, mood: 'somber',
    firstFrame: 'IT NEVER CAME BACK',
    hook: 'Something you built will outlive your entire species.',
    beats: [
      B(0, 'Something you built will outlive your entire species.', 'neutral', 'none', ''),
      B(6, 'In 1977 you threw a machine off the planet. It never came back.', 'scan', 'none', ''),
      B(12, 'It left the solar system while you were arguing on the internet.', 'smirk', 'zoom', 'dry'),
      B(18, 'In forty thousand years it passes another star. Your cities will be dust.', 'sad', 'none', ''),
      B(25, 'It carries a gold record of Earth sounds. A hello from people already gone.', 'neutral', 'flare', 'soften'),
    ],
    loopLine: 'I passed it out here. I did not wave. It would not have mattered.',
    videoTitle: 'The Machine That Will Outlive Humanity',
    description: 'Voyager 1 launched in 1977, crossed into interstellar space in 2012, carries the Golden Record, and passes near another star in roughly 40,000 years.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['voyager 1', 'golden record', 'nasa', 'interstellar space', 'space facts', 'astronomy', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'Voyager will outlive all of us. It carries our voice. #voyager #space #shorts',
    pinnedComment: 'One sound you would put on the record. One only. Go.',
    factCheck: 'Voyager 1 launched 1977, entered interstellar space 2012, carries the Golden Record, passes AC+79 3888 in ~40,000 years.',
    whyItWorks: 'Pride plus grief in the same thirty seconds is the strongest share combination on space content. The "arguing on the internet" beat is a laugh that buys the emotional beat that follows.',
  },

  // ============ PILLAR: MYSTERY (11-18) ============
  {
    id: 16, number: 16, pillar: 'mystery', title: 'Two Hundred Billion Stars. Nobody Home.', world: 'nebula-drift', durationSec: 30, mood: 'somber',
    firstFrame: 'NOBODY IS HOME',
    hook: 'Two hundred billion stars in this galaxy. Nobody is home.',
    beats: [
      B(0, 'Two hundred billion stars in this galaxy. Nobody is home.', 'neutral', 'none', ''),
      B(6, 'The maths says thousands of worlds should be talking.', 'scan', 'none', ''),
      B(11, 'We have listened for seventy years. We have heard nothing.', 'neutral', 'zoom', ''),
      B(17, 'Maybe life is rare. Maybe it is hiding. Maybe loud worlds do not last.', 'narrow', 'static', 'three options, slow'),
      B(24, 'I have flown far enough to have a favourite answer.', 'smirk', 'glitch', ''),
    ],
    loopLine: 'My answer is: keep your volume down. Two hundred billion stars just heard that.',
    videoTitle: 'Two Hundred Billion Stars And Nobody Is Home',
    description: 'The Fermi paradox: the gap between how much life should exist and how little evidence we find. Modern SETI has been listening since 1960.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['fermi paradox', 'aliens', 'seti', 'space mystery', 'astrobiology', 'space facts', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'The sky should be crowded. It is silent. #fermiparadox #aliens #space #shorts',
    pinnedComment: 'Rare, hiding, or dead? Pick one word. Biggest group gets its own transmission.',
    factCheck: 'Fermi paradox: tension between high estimates for extraterrestrial life and the absence of evidence.',
    whyItWorks: 'The three-option beat is engineered comment bait — it hands the viewer a ready-made one-word reply, which is the cheapest possible comment to leave and the fastest signal to trigger.',
  },
  {
    id: 17, number: 17, pillar: 'mystery', title: 'The Test Almost Nobody Survives', world: 'asteroid-earth', durationSec: 30, mood: 'urgent',
    firstFrame: 'BEHIND US OR AHEAD?',
    hook: 'There is one test every civilisation takes. Almost nobody passes.',
    beats: [
      B(0, 'There is one test every civilisation takes. Almost nobody passes.', 'neutral', 'none', ''),
      B(6, 'Something kills them all at the same step. A filter.', 'scan', 'none', ''),
      B(11, 'Nobody knows which step it is. That is the whole problem.', 'neutral', 'zoom', ''),
      B(17, 'If humans already passed it, you are a miracle. The sky is empty because you won.', 'narrow', 'none', ''),
      B(24, 'If it is still ahead of you, the silence out here is a warning.', 'anger', 'static', 'cold'),
    ],
    loopLine: 'I have been further out than anyone. I know which one it is. Ask me again.',
    videoTitle: 'The Test Almost No Civilisation Survives',
    description: 'The Great Filter (Robin Hanson, 1996): some step between dead matter and a galaxy-spanning civilisation that almost nothing gets past. Nobody knows whether it is behind us or in front.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['great filter', 'fermi paradox', 'existential risk', 'space mystery', 'aliens', 'space facts', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'Behind us we are a miracle. Ahead of us we are next. #greatfilter #space #shorts',
    pinnedComment: 'Filter behind us or ahead of us? Two options. Defend yours in one line.',
    factCheck: 'Great Filter hypothesis (Robin Hanson, 1996).',
    whyItWorks: 'Frames an abstraction as a personal verdict on the viewer\'s own species, then withholds the answer. Withholding is what earns the follow — the payoff is promised to a future transmission, not to this video.',
  },
  {
    id: 18, number: 18, pillar: 'mystery', title: 'The Universe Has No Edge. It Has A Deadline.', world: 'nebula-drift', durationSec: 29, mood: 'somber',
    firstFrame: 'THERE IS NO EDGE',
    hook: 'I flew toward the edge of the universe. There is no edge.',
    beats: [
      B(0, 'I flew toward the edge of the universe. There is no edge.', 'neutral', 'none', ''),
      B(6, 'Whichever way I go, more universe grows in front of me.', 'scan', 'none', ''),
      B(11, 'Space itself stretches. Far enough away, it stretches faster than light travels.', 'neutral', 'zoom', ''),
      B(18, 'Those places can never reach you again. Not in any amount of time.', 'narrow', 'none', ''),
      B(24, 'The edge of the universe is not a wall. It is a deadline.', 'sad', 'pulse', 'let it sit'),
    ],
    loopLine: 'While you watched this, more of it went past that deadline. Forever. Again.',
    videoTitle: 'The Universe Has No Edge. It Has A Deadline.',
    description: 'Metric expansion means sufficiently distant regions recede faster than light and permanently leave our observable universe. The horizon is a limit on time, not a boundary in space.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['expanding universe', 'cosmology', 'observable universe', 'space mystery', 'space facts', 'astronomy', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'It is not a wall. It is a deadline. #universe #cosmology #space #shorts',
    pinnedComment: 'Something out there just left forever. Does that scare you or not? One word.',
    factCheck: 'Metric expansion of space; superluminal recession beyond the Hubble sphere; cosmological event horizon.',
    whyItWorks: 'The reframe in the final beat ("a deadline") gives an old topic a new sentence, which is what makes it re-postable. The loop line makes the loss happen during the video, so the rewatch feels urgent instead of optional.',
  },
  {
    id: 19, number: 19, pillar: 'mystery', title: 'The Universe Could End Mid-Sentence', world: 'dying-star', durationSec: 29, mood: 'urgent',
    firstFrame: 'NO WARNING',
    hook: 'The universe could end before I finish this sentence.',
    beats: [
      B(0, 'The universe could end before I finish this sentence.', 'neutral', 'none', 'dead calm'),
      B(5, 'Empty space might not be stable. It might just be resting.', 'scan', 'none', ''),
      B(11, 'If one point ever slips, a bubble of new rules spreads at light speed.', 'narrow', 'zoom', ''),
      B(18, 'It rewrites everything it touches. Atoms. Planets. You.', 'shock', 'static', ''),
      B(23, 'There is no warning, because the warning arrives with it.', 'neutral', 'none', 'flat'),
    ],
    loopLine: 'The good news is you would never know. Start the sentence again.',
    videoTitle: 'The Universe Could End Mid-Sentence',
    description: 'If the Higgs vacuum is metastable, false vacuum decay could expand at light speed with no forewarning. It has not happened in 13.8 billion years.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['vacuum decay', 'false vacuum', 'higgs', 'end of the universe', 'physics', 'space facts', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'No alarm. No time. You would never know. #vacuumdecay #physics #space #shorts',
    pinnedComment: 'One guaranteed last day, no fear, no pain. How do you spend it?',
    factCheck: 'False vacuum decay is a hypothesised possibility if the electroweak vacuum is metastable.',
    whyItWorks: 'The title promise is structural: the video must finish for the joke to land, which is a retention mechanism written into the premise. The pinned question is emotional rather than factual, and emotional prompts get far longer comments.',
  },
  {
    id: 20, number: 20, pillar: 'mystery', title: 'Most Of Everything Is Invisible', world: 'nebula-drift', durationSec: 29, mood: 'hero',
    firstFrame: '85% MISSING',
    hook: 'Most of the universe is missing, and it is passing through you.',
    beats: [
      B(0, 'Most of the universe is missing. And it is passing through you.', 'neutral', 'none', ''),
      B(6, 'Galaxies spin too fast. They should have flown apart long ago.', 'scan', 'none', ''),
      B(11, 'Something invisible is holding them together. Five times more of it than everything we see.', 'neutral', 'zoom', ''),
      B(18, 'It goes through walls, through planets, through your chest. Silently.', 'narrow', 'static', ''),
      B(24, 'You are the rare kind of matter. The kind that can be seen.', 'smirk', 'pulse', ''),
    ],
    loopLine: 'The universe is mostly made of things that never look back. Mostly.',
    videoTitle: '85% Of The Universe Is Invisible And Inside You',
    description: 'Dark matter makes up roughly 85% of the matter in the universe, inferred from galaxy rotation curves and gravitational lensing. It has never been directly detected.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['dark matter', 'galaxy rotation', 'cosmology', 'space mystery', 'physics', 'space facts', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'It is going through your chest right now. #darkmatter #space #shorts #SpaceSpidey',
    pinnedComment: 'If dark matter could think, what does it think of you? One line.',
    factCheck: 'Dark matter is ~85% of matter content; evidence from rotation curves, lensing and structure formation.',
    whyItWorks: 'Puts the phenomenon inside the viewer\'s body by beat four — invasion is more compelling than scale. The flattering final beat ("you are the rare kind") is what converts an unsettling fact into a like.',
  },
  {
    id: 21, number: 21, pillar: 'mystery', title: 'You Freeze Forever And Fall In Seconds', world: 'dying-star', durationSec: 30, mood: 'urgent',
    firstFrame: 'BOTH ARE TRUE',
    hook: 'Nobody has ever seen anything fall into a black hole. Ever.',
    beats: [
      B(0, 'Nobody has ever seen anything fall into a black hole. Ever.', 'neutral', 'none', ''),
      B(6, 'From outside, you slow down. Redden. Freeze at the edge. Forever.', 'scan', 'zoom', ''),
      B(12, 'From inside your own body, you fall straight through in seconds.', 'narrow', 'none', ''),
      B(18, 'Then gravity pulls you into a thread of atoms. Scientists really named it spaghettification.', 'shock', 'shake', ''),
      B(25, 'Frozen forever. Gone in seconds. Both are true at the same time.', 'neutral', 'static', ''),
    ],
    loopLine: 'The universe cannot agree on how you died. Go back and pick a side.',
    videoTitle: 'You Freeze Forever AND Fall In Seconds. Both Are True.',
    description: 'Two observers, two valid descriptions: extreme gravitational time dilation for the distant watcher, a short proper-time infall for the faller. Tidal stretching does the rest.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['black hole', 'relativity', 'event horizon', 'spaghettification', 'physics', 'space facts', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'Two truths, one death. #blackhole #relativity #space #shorts #SpaceSpidey',
    pinnedComment: 'Frozen at the edge forever, or gone in ten seconds? Choose your death.',
    factCheck: 'Frame-dependent descriptions of infall; both are physically correct. Tidal spaghettification is the standard term.',
    whyItWorks: 'A genuine paradox invites argument, and argument is comment volume. The pinned comment forces a choice between two vivid deaths, which is the highest-response prompt format on this channel.',
  },
  {
    id: 22, number: 22, pillar: 'mystery', title: 'Something Out Here Keeps Perfect Time', world: 'derelict-station', durationSec: 29, mood: 'urgent',
    firstFrame: 'EVERY 16 DAYS',
    hook: 'Something out here sends the same signal every sixteen days.',
    beats: [
      B(0, 'Something out here sends the same signal every sixteen days.', 'neutral', 'none', ''),
      B(6, 'A radio flash shorter than a blink, brighter than your sun screaming.', 'scan', 'none', ''),
      B(12, 'Four days of bursts. Twelve days of silence. Then again. Exactly.', 'narrow', 'zoom', ''),
      B(19, 'Probably a dead star with a monstrous magnetic field. Probably.', 'neutral', 'static', ''),
      B(24, 'But when something keeps perfect time, you ask who is holding the clock.', 'anger', 'glitch', ''),
    ],
    loopLine: 'By my count, today is day fifteen. Come back tomorrow. Or watch this again.',
    videoTitle: 'The Space Signal That Repeats Every 16 Days',
    description: 'FRB 180916.J0158+65 repeats on a ~16.35-day cycle (CHIME, 2020). Leading explanations involve magnetars or binary systems. It has never been fully explained.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['fast radio burst', 'frb', 'space signal', 'space mystery', 'aliens', 'astronomy', 'space facts', 'science shorts', 'universe', 'shorts'],
    caption: 'A signal on a perfect 16-day loop. #frb #spacemystery #space #shorts',
    pinnedComment: 'Natural clock, or somebody\u2019s clock? Vote. I read every reply on this one.',
    factCheck: 'FRB 180916.J0158+65 repeats with a ~16.35-day periodicity (CHIME/FRB, 2020).',
    whyItWorks: 'The "day fifteen" loop line manufactures a reason to return tomorrow, which is the only line in this pillar that builds a habit instead of a view. Keeping the catalog number out of the audio protects the share.',
  },
  {
    id: 23, number: 23, pillar: 'mystery', title: 'The Star That Kept Switching Off', world: 'nebula-drift', durationSec: 29, mood: 'hero',
    firstFrame: 'IT KEPT GOING DARK',
    hook: 'A star kept switching itself off, and no planet can do that.',
    beats: [
      B(0, 'A star kept switching itself off. No planet can do that.', 'neutral', 'none', ''),
      B(6, 'It lost a fifth of its light. At random. In no pattern at all.', 'scan', 'none', ''),
      B(12, 'A planet blocks a fraction of a percent. This was a fifth.', 'neutral', 'zoom', 'hit the contrast'),
      B(18, 'For two years, real scientists wrote the words alien megastructure in real papers.', 'smirk', 'none', ''),
      B(25, 'The answer now is probably dust. Probably.', 'narrow', 'pulse', ''),
    ],
    loopLine: 'For two years Earth genuinely wondered if someone was building. Remember that feeling.',
    videoTitle: 'The Star That Made Scientists Say "Megastructure"',
    description: 'KIC 8462852 (Boyajian\u2019s Star) showed irregular dips of up to ~22% in brightness. Dust is the leading explanation; the megastructure hypothesis was seriously published.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['tabbys star', 'boyajians star', 'alien megastructure', 'dyson sphere', 'space mystery', 'astronomy', 'space facts', 'science shorts', 'universe', 'shorts'],
    caption: 'Scientists said megastructure. Out loud. In papers. #space #aliens #shorts',
    pinnedComment: 'If someone built around a star, what were they building it FOR? Best theory wins a transmission.',
    factCheck: 'KIC 8462852 dips up to ~22%; dust/debris is the leading explanation; megastructure hypotheses were published in 2015-2016.',
    whyItWorks: 'The percentage contrast in beat three is the proof that stops the scroll — it shows the viewer why professionals panicked, instead of just telling them a story about aliens.',
  },

  // ============ PILLAR: ANSWERS (19-23) ============
  {
    id: 24, number: 24, pillar: 'answers', title: 'You Asked If I Am Human', world: 'derelict-station', durationSec: 28, mood: 'somber',
    firstFrame: 'AM I HUMAN?',
    hook: 'You asked if there is still a human under this mask.',
    beats: [
      B(0, 'You asked if there is still a human under this mask.', 'neutral', 'none', 'as if reading a comment'),
      B(6, 'I remember rain. A door with peeling paint. Someone laughing behind it.', 'sad', 'none', 'slow'),
      B(13, 'I do not remember their name. I have tried for years.', 'narrow', 'static', ''),
      B(19, 'The suit keeps me alive. The mask keeps me consistent.', 'neutral', 'zoom', ''),
      B(24, 'Human is a word for people who still live where you live.', 'sad', 'none', ''),
    ],
    loopLine: 'Ask me again when I remember who was behind that door.',
    videoTitle: 'Am I Still Human? You Asked. Here Is The Answer.',
    description: 'Answering the most-asked question in the comments. Lore.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['spacespidey', 'lore', 'space horror', 'scifi', 'character', 'storytime', 'space', 'shorts', 'series', 'transmission'],
    caption: 'You asked. Here is what is left under the mask. #SpaceSpidey #lore #shorts',
    pinnedComment: 'Who was behind the door? First theory that fits becomes canon.',
    factCheck: 'fiction: lore',
    whyItWorks: 'Answer videos are the cheapest loyalty machine on the channel: the viewer sees their own question become content. The forgotten name is a deliberate gap the audience gets to fill, which is how a comment section becomes a co-author.',
  },
  {
    id: 25, number: 25, pillar: 'answers', title: 'What I Eat Out Here', world: 'red-planet', durationSec: 26, mood: 'hero',
    firstFrame: 'YOU ASKED. BAD IDEA.',
    hook: 'You asked what I eat out here. You will regret it.',
    beats: [
      B(0, 'You asked what I eat out here. You will regret it.', 'smirk', 'none', ''),
      B(5, 'The suit recycles everything. Water. Heat. Breath. Yes, that too.', 'neutral', 'none', 'deadpan'),
      B(11, 'Food is a paste grown from algae and printed protein.', 'narrow', 'zoom', ''),
      B(16, 'It tastes like wet paper that gave up.', 'smirk', 'none', 'land the joke'),
      B(21, 'Your astronauts drink recycled sweat. Yesterday\u2019s coffee is tomorrow\u2019s coffee.', 'neutral', 'pulse', ''),
    ],
    loopLine: 'Name one Earth meal worth crossing four light-years for. I am serious.',
    videoTitle: 'What You Actually Eat In Deep Space',
    description: 'The ISS recycles over 90% of its water, including urine and sweat. Algae and printed protein are both active space-food research lines.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['astronaut food', 'iss', 'space station', 'recycled water', 'space facts', 'nasa', 'science shorts', 'space', 'shorts', 'spacespidey'],
    caption: 'Yesterday\u2019s coffee is tomorrow\u2019s coffee. #astronaut #space #shorts #SpaceSpidey',
    pinnedComment: 'One Earth meal worth four light-years. Name it. Most-named food becomes canon.',
    factCheck: 'ISS water recovery exceeds 90% including urine and sweat processing.',
    whyItWorks: 'Comedy is the release valve in a channel built on dread — it widens the audience and keeps the feed from typecasting the account as horror only. The pinned question asks for a food, which is the single easiest comment anyone can leave.',
  },
  {
    id: 26, number: 26, pillar: 'answers', title: 'Can You Actually See Earth From There?', world: 'asteroid-earth', durationSec: 27, mood: 'somber',
    firstFrame: 'THAT DOT IS YOU',
    hook: 'You asked if I can see Earth from here. That dot. Right there.',
    beats: [
      B(0, 'You asked if I can see Earth from here. That dot. Right there.', 'neutral', 'none', 'gesture behind'),
      B(6, 'Everyone you have ever met is inside that one point of light.', 'sad', 'zoom', ''),
      B(12, 'Every war. Every song. Every first kiss. One pixel.', 'neutral', 'none', ''),
      B(18, 'No borders are visible from here. Not one. They were never there.', 'narrow', 'none', ''),
      B(23, 'It looks small enough to cover with a thumb.', 'sad', 'pulse', 'soften'),
    ],
    loopLine: 'So why does something that small feel too far away to save? Look again.',
    videoTitle: 'What Earth Looks Like From Very Far Away',
    description: 'Voyager 1 photographed Earth as a single pixel from about 6 billion kilometres on 14 February 1990 — the Pale Blue Dot.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['pale blue dot', 'voyager', 'earth from space', 'carl sagan', 'overview effect', 'space facts', 'science shorts', 'universe', 'shorts', 'spacespidey'],
    caption: 'Every person you know fits in one pixel. #palebluedot #earth #space #shorts',
    pinnedComment: 'Write the caption for that photo in one sentence. Best one gets pinned next week.',
    factCheck: 'Voyager 1 Pale Blue Dot image, 14 Feb 1990, from ~6 billion km.',
    whyItWorks: 'The borders beat is the political-emotional spike that makes this the most shareable script in the pillar. Promising to pin the best reply next week converts commenters into returning viewers.',
  },
  {
    id: 27, number: 27, pillar: 'answers', title: 'Why I Cannot Come Home', world: 'nebula-drift', durationSec: 28, mood: 'urgent',
    firstFrame: 'STOP ASKING ME',
    hook: 'You keep asking why I do not just come home. Fine.',
    beats: [
      B(0, 'You keep asking why I do not just come home. Fine.', 'neutral', 'none', ''),
      B(6, 'Distance is not the problem. Four light-years is only a long walk.', 'scan', 'none', ''),
      B(12, 'Something followed me out of the dark. It reads the path I leave behind.', 'narrow', 'static', 'lower the voice'),
      B(19, 'If I point this suit at Earth, I draw it a map.', 'anger', 'glitch', ''),
      B(24, 'So I stay lost. That is the whole answer.', 'sad', 'none', ''),
    ],
    loopLine: 'I stay lost so you stay found. Please stop asking me to come home.',
    videoTitle: 'Why I Can Never Come Back To Earth',
    description: 'Lore. The reason there is no return trip.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['spacespidey', 'lore', 'space horror', 'scifi series', 'storytime', 'cliffhanger', 'space', 'shorts', 'character', 'transmission'],
    caption: 'I stay lost so you stay found. #SpaceSpidey #lore #space #shorts',
    pinnedComment: 'What kind of thing can read a ship\u2019s path? Theories. I am reading all of them.',
    factCheck: 'fiction: lore',
    whyItWorks: 'A refusal is more interesting than an explanation. The line "I stay lost so you stay found" is written to be screenshotted, which is how lore episodes recruit viewers who never watch the science ones.',
  },
  {
    id: 28, number: 28, pillar: 'answers', title: 'The Scariest Thing I Have Found', world: 'dying-star', durationSec: 29, mood: 'urgent',
    firstFrame: 'IT WAS CLEAN',
    hook: 'The scariest thing I have found out here was not a black hole.',
    beats: [
      B(0, 'The scariest thing out here was not a black hole.', 'neutral', 'none', ''),
      B(6, 'Black holes are honest. They tell you exactly what they will do.', 'scan', 'none', ''),
      B(12, 'I found a region with no dust. No signal. Not even the background hum.', 'narrow', 'zoom', ''),
      B(19, 'Everything in this universe leaves a trace. That place had none.', 'shock', 'static', ''),
      B(25, 'It was not empty. It was cleaned.', 'anger', 'glitch', 'whisper'),
    ],
    loopLine: 'I marked the coordinates. Something in there was still watching. Play it again.',
    videoTitle: 'The Scariest Thing In Space Is A Clean Spot',
    description: 'Lore, built on a real idea: everything in the universe leaves a signature. Cosmic voids exist, but they are never truly featureless.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['space horror', 'spacespidey', 'lore', 'cosmic void', 'creepy space', 'scifi series', 'storytime', 'space', 'shorts', 'cliffhanger'],
    caption: 'It was not empty. It was cleaned. #spacehorror #SpaceSpidey #shorts',
    pinnedComment: 'What erases every trace of matter from a whole region? Wrong answers might be right.',
    factCheck: 'fiction: lore (real cosmic voids such as the Bo\u00f6tes Void exist but contain sparse galaxies)',
    whyItWorks: 'Absence is scarier than a monster, and it costs nothing to render. "It was cleaned" is a two-word turn that reliably produces reply-threads arguing about what did the cleaning.',
  },

  // ============ PILLAR: LORE (24-27) ============
  {
    id: 29, number: 29, pillar: 'lore', title: 'Thirty-Nine Suits Went Dark', world: 'derelict-station', durationSec: 30, mood: 'somber',
    firstFrame: 'MINE STAYED AWAKE',
    hook: 'Forty of us launched. Thirty-nine suits went dark on the pad.',
    beats: [
      B(0, 'Forty of us launched. Thirty-nine suits went dark on the pad.', 'neutral', 'none', ''),
      B(6, 'There was a program you never read about. Forty one-way tickets.', 'scan', 'none', ''),
      B(12, 'They did not build the suits. They found the material. Already woven.', 'narrow', 'static', 'touch the red lines'),
      B(19, 'Launch day, thirty-nine went silent in nine seconds. Mine stayed awake.', 'shock', 'glitch', ''),
      B(25, 'I did not volunteer to be the one who lived.', 'sad', 'zoom', ''),
    ],
    loopLine: 'The suit chose me. The answer is stitched into these red threads. Count them.',
    videoTitle: 'Thirty-Nine Suits Went Dark. Mine Did Not.',
    description: 'LORE DROP 001 — the launch. Where the suit came from, and why there is only one of me.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['spacespidey', 'lore', 'origin story', 'space horror', 'scifi series', 'storytime', 'cliffhanger', 'space', 'shorts', 'character'],
    caption: 'LORE 001 — thirty-nine went dark. #SpaceSpidey #lore #origin #shorts',
    pinnedComment: 'Why did the suit pick me? First theory that holds up gets woven into the story.',
    factCheck: 'fiction: lore',
    whyItWorks: 'Opens on the number, not the backstory — the mystery is the hook and the exposition arrives after the viewer is committed. "Count them" gives obsessive viewers a job, and jobs produce long comments.',
  },
  {
    id: 30, number: 30, pillar: 'lore', title: 'What The Red Threads Actually Are', world: 'nebula-drift', durationSec: 29, mood: 'hero',
    firstFrame: 'NOT DECORATION',
    hook: 'You keep asking about the red threads. Listen once.',
    beats: [
      B(0, 'You keep asking about the red threads on this suit. Listen once.', 'neutral', 'none', ''),
      B(6, 'They are not decoration. They are not wiring. They are older than both.', 'scan', 'none', ''),
      B(12, 'There is a web strung between galaxies. Real. Mapped. Your scientists see it.', 'narrow', 'pulse', 'trace a line'),
      B(19, 'They call it the cosmic web and think it is only gravity and gas.', 'neutral', 'zoom', ''),
      B(25, 'These threads do not glow. They answer it.', 'surge', 'flare', ''),
    ],
    loopLine: 'And tonight, something pulled the web before I did. Watch that again.',
    videoTitle: 'What The Red Threads On The Suit Really Are',
    description: 'LORE DROP 002 — the Weave. The cosmic web of galaxy filaments is real large-scale structure. The rest is lore.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['cosmic web', 'spacespidey', 'lore', 'galaxy filaments', 'scifi series', 'space facts', 'storytime', 'space', 'shorts', 'character'],
    caption: 'The cosmic web is real. Look it up. #cosmicweb #SpaceSpidey #lore #shorts',
    pinnedComment: 'The web between galaxies is real, Earth. So what walks on a web?',
    factCheck: 'fiction: lore (the cosmic web of galaxy filaments is genuine large-scale structure)',
    whyItWorks: 'Welds the character to a real, searchable phenomenon — viewers who go and confirm the cosmic web come back trusting the channel. "What walks on a web" is the spider question the whole brand is built on.',
  },
  {
    id: 31, number: 31, pillar: 'lore', title: 'The Thing That Follows Me', world: 'dying-star', durationSec: 30, mood: 'urgent',
    firstFrame: 'IT IS CLOSER TONIGHT',
    hook: 'It is closer tonight, so I will say this fast.',
    beats: [
      B(0, 'It is closer tonight, so I will say this fast.', 'narrow', 'static', 'urgent, controlled'),
      B(5, 'It does not travel through space. It travels through absence.', 'scan', 'glitch', ''),
      B(11, 'The clean region I told you about. I left out one detail.', 'neutral', 'zoom', ''),
      B(18, 'It was not empty when I arrived. It was empty when I left.', 'shock', 'shake', 'pause. let it land.'),
      B(25, 'The suit will not say its name. The threads go quiet when I ask.', 'sad', 'static', ''),
    ],
    loopLine: 'If a transmission ever stops mid-sentence, do not look for me. Look up.',
    videoTitle: 'The Thing That Has Been Following Me',
    description: 'LORE DROP 003 — the Follower. It moves through the places where nothing is left.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['space horror', 'spacespidey', 'lore', 'creepy space', 'scifi series', 'cliffhanger', 'storytime', 'space', 'shorts', 'character'],
    caption: 'Do not look for me. Look up. #spacehorror #SpaceSpidey #lore #shorts',
    pinnedComment: 'It erases everything it touches. Except me. Why me? Say it out loud.',
    factCheck: 'fiction: lore',
    whyItWorks: 'The retroactive reveal ("I left out one detail") rewards anyone who saw the earlier transmission and sends new viewers hunting for it, which is the only mechanic that turns Shorts views into channel views.',
  },
  {
    id: 32, number: 32, pillar: 'lore', title: 'Suit Thirty-One Is Still Out There', world: 'derelict-station', durationSec: 30, mood: 'urgent',
    firstFrame: 'I AM NOT THE ONLY ONE',
    hook: 'I was not the only survivor. Someone wrote a number in the dust.',
    beats: [
      B(0, 'I was not the only survivor. Someone wrote a number in the dust.', 'neutral', 'none', ''),
      B(6, 'I found this station cycles ago. The airlock was already open.', 'scan', 'zoom', ''),
      B(12, 'No bodies. No logs. Just two digits on a dead console.', 'neutral', 'none', ''),
      B(18, 'Thirty-one. One of the thirty-nine suits that went dark on the pad.', 'shock', 'static', ''),
      B(25, 'So it did not die. It went somewhere. And the dust was fresh.', 'anger', 'shake', ''),
    ],
    loopLine: 'Suit thirty-one. If you are receiving this, you know which thread to pull.',
    videoTitle: 'Suit Thirty-One Is Still Alive',
    description: 'LORE DROP 004 — Suit 31. Somebody else got off that launch pad.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['spacespidey', 'lore', 'space horror', 'scifi series', 'cliffhanger', 'storytime', 'mystery', 'space', 'shorts', 'character'],
    caption: 'Someone else survived the launch. #SpaceSpidey #lore #mystery #shorts',
    pinnedComment: 'Do I trust Suit Thirty-One or not? The comments decide what I do next.',
    factCheck: 'fiction: lore',
    whyItWorks: 'Handing the decision to the audience is the strongest retention device a serialized channel has — the next episode becomes something they voted for, so they come back to see whether they won.',
  },

  // ============ PILLAR: TREND (28-30) ============
  {
    id: 33, number: 33, pillar: 'trend', title: 'POV: Your Last Thirty Seconds Of Signal', world: 'red-planet', durationSec: 28, mood: 'somber',
    firstFrame: '30 SECONDS LEFT',
    hook: 'You get one last message to Earth. Thirty seconds. Go.',
    beats: [
      B(0, 'You get one last message to Earth. Thirty seconds. Signal is dying. Go.', 'neutral', 'static', 'countdown energy'),
      B(7, 'You do not talk about the mission. Nobody ever does.', 'sad', 'none', ''),
      B(13, 'You say: leave the kitchen window open in summer. The cat likes it.', 'neutral', 'zoom', 'tiny human detail'),
      B(20, 'That is what thirty seconds is for. The small things were the big things.', 'sad', 'pulse', ''),
    ],
    loopLine: 'Signal restored. This time. What would your thirty seconds say?',
    videoTitle: 'POV: Your Last Thirty Seconds Of Signal',
    description: 'A format piece. One final transmission home, and what people actually spend it on.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['pov', 'space', 'emotional', 'storytime', 'scifi', 'spacespidey', 'shorts', 'sad', 'trend', 'transmission'],
    caption: 'Thirty seconds. What do you say? #pov #space #shorts #SpaceSpidey',
    pinnedComment: 'Write your thirty seconds below. I will read the best one on air, in full.',
    factCheck: 'fiction: format piece',
    whyItWorks: 'The comment section becomes the content, and "I will read the best one on air" is a genuine reward rather than an ask. The mundane detail (a cat, a window) is what makes people cry, and crying is what makes people share.',
  },
  {
    id: 34, number: 34, pillar: 'trend', title: 'Space Facts That Feel Illegal', world: 'nebula-drift', durationSec: 28, mood: 'hero',
    firstFrame: 'NUMBER FOUR IS WORSE',
    hook: 'Four things about your body in space that feel illegal.',
    beats: [
      B(0, 'Four things about your body in space that feel illegal. One.', 'smirk', 'none', 'fast list energy'),
      B(5, 'Crying is dangerous. Tears do not fall. They stick to your eyes like glass.', 'neutral', 'zoom', ''),
      B(11, 'Two. You get taller. Your spine unfolds up to five centimetres.', 'scan', 'pulse', ''),
      B(17, 'Three. Sixteen sunrises a day. By day three you stop watching them.', 'neutral', 'flare', ''),
      B(23, 'Four. Silence so complete your own heartbeat sounds like footsteps.', 'narrow', 'static', ''),
    ],
    loopLine: 'There is a fifth. I wish I did not know it. Start again from one.',
    videoTitle: 'Four Space Facts That Feel Illegal',
    description: 'Tears pool in microgravity, astronauts gain 3-5cm in height, and the ISS sees roughly 16 sunrises a day.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['space facts', 'astronaut', 'iss', 'human body', 'microgravity', 'listicle', 'science shorts', 'space', 'shorts', 'spacespidey'],
    caption: 'Number four is the one that stays with you. #spacefacts #astronaut #shorts',
    pinnedComment: 'Which one broke your brain? Number five stays classified until someone guesses it.',
    factCheck: 'Tears adhere in microgravity; astronauts gain ~3-5cm spinal height; ISS observes ~16 sunrises daily.',
    whyItWorks: 'Numbered lists are the highest-retention Shorts format because each number is a promise of an end, and the withheld fifth item is an unresolved loop that both drives comments and justifies the rewatch.',
  },
  {
    id: 35, number: 35, pillar: 'trend', title: 'Rating Your Planets', world: 'asteroid-earth', durationSec: 30, mood: 'hero',
    firstFrame: 'RATING YOUR PLANETS',
    hook: 'I flew through your solar system. Rating the planets. Honestly.',
    beats: [
      B(0, 'I flew through your solar system once. Rating your planets. Honestly.', 'smirk', 'none', 'fun, still deadpan'),
      B(5, 'Mercury. A cannonball with anxiety. Four out of ten.', 'neutral', 'zoom', ''),
      B(10, 'Venus. Nine hundred degrees, acid clouds, gorgeous. Beautiful liar. Seven.', 'narrow', 'pulse', ''),
      B(16, 'Jupiter. Takes the hits meant for you. Bodyguard nobody thanks. Nine.', 'scan', 'flare', ''),
      B(22, 'Saturn. Wears dead moons as jewellery. Unnecessary. Flawless. Ten.', 'shock', 'none', ''),
      B(27, 'Earth. Loud. Fragile. Mine. No rating.', 'sad', 'zoom', 'soften'),
    ],
    loopLine: 'I do not rate the things I am still trying to get back to. Replay that.',
    videoTitle: 'Rating Your Solar System, Honestly',
    description: 'Venus is about 465C with sulfuric acid clouds. Jupiter absorbs and deflects impactors. Saturn\u2019s rings are mostly water ice from shattered bodies.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['planets', 'solar system', 'rating', 'space facts', 'jupiter', 'saturn', 'venus', 'science shorts', 'shorts', 'spacespidey'],
    caption: 'Saturn wears dead moons as jewellery. Ten out of ten. #planets #space #shorts',
    pinnedComment: 'Which rating did I get wrong? Defend your planet. I am watching.',
    factCheck: 'Venus surface ~465C with sulfuric acid clouds; Jupiter deflects/absorbs many impactors; Saturn\u2019s rings are mostly water ice.',
    whyItWorks: 'Ratings invite disagreement, and disagreement is the highest-volume comment type that exists. Withholding Earth\u2019s score is the emotional turn that stops it being just a joke video.',
  },
];

/* ============ THE LAUNCH SEQUENCE — the first five uploads ============
   These five already went out and underperformed. Diagnosis, per script, in
   `postmortem`. What changed in v2, in every case:
     - the hook lost its run-up and now lands in under two seconds
     - the character stopped explaining and started accusing ("you", first word)
     - every number became a comparison a nine-year-old can picture
     - the closing line is now a loop plus an instruction, not a musing
     - the pinned comment became a binary, so replying costs one word
   Re-shoot in this order, one every 48 hours, same hour each time. */
export const LAUNCH_SEQUENCE = [
  {
    id: 1, number: 1, pillar: 'launch', publishOrder: 1, best: true, status: 'reshoot',
    title: 'LAUNCH 1 · The Sun Could Already Be Dead', world: 'asteroid-earth', durationSec: 27, mood: 'urgent',
    firstFrame: 'IT MIGHT BE GONE',
    hook: 'The sun could be dead right now. You would not know.',
    beats: [
      B(0, 'The sun could be dead right now. You would not know.', 'neutral', 'none', 'dead still, quiet menace'),
      B(5, 'Its light needs eight minutes and twenty seconds to reach your face.', 'scan', 'none', 'slow turn toward Earth'),
      B(11, 'Nothing warns you faster. Not light. Not gravity. Nothing.', 'neutral', 'zoom', 'punch in'),
      B(17, 'So you would keep texting, laughing, breathing, in a world already over.', 'sad', 'none', 'let it land'),
      B(23, 'That warmth on your skin is history. Touching you.', 'narrow', 'pulse', 'soften, look down'),
    ],
    loopLine: 'Go check the sky. Still there? As of eight minutes ago. Watch again.',
    videoTitle: 'The Sun Could Already Be Dead',
    description: 'Sunlight takes 8 minutes 20 seconds to cross 1 AU, and no signal of any kind travels faster. The sun you see is never the sun that is.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['the sun', 'speed of light', 'space facts', 'astronomy', 'mind blowing facts', 'science shorts', 'universe', 'space', 'shorts', 'spacespidey'],
    caption: 'You are always eight minutes behind your own star. #space #sun #shorts',
    pinnedComment: 'Eight minutes of warning. Would you want to be told? Yes or no.',
    factCheck: 'Sunlight travel time ~8 min 20 s (1 AU / c); no signal, including gravitational, propagates faster than c.',
    postmortem: 'v1 opened with a conditional ("If your sun died right now") which reads as hypothetical and gets swiped. v2 opens with a flat claim about the present moment, which the brain has to check.',
    whyItWorks: 'Zero prior knowledge required, personal stakes in the first sentence, and a closing line that physically sends the viewer to a window and back to the replay. This stays upload one.',
  },
  {
    id: 2, number: 2, pillar: 'launch', publishOrder: 2, status: 'reshoot',
    title: 'LAUNCH 2 · You Are Faster Than A Bullet', world: 'nebula-drift', durationSec: 26, mood: 'urgent',
    firstFrame: 'YOU ARE NOT STILL',
    hook: 'You are moving faster than a bullet. Right now.',
    beats: [
      B(0, 'You are moving faster than a bullet. Right now. Sitting there.', 'neutral', 'none', 'lean in, dead serious'),
      B(5, 'The ground under you is spinning. You have never felt it once.', 'scan', 'zoom', 'point down'),
      B(10, 'Earth is also racing around the sun. Thirty times a bullet\u2019s speed.', 'neutral', 'pulse', ''),
      B(15, 'And the sun is falling through the galaxy, dragging you along.', 'surge', 'shake', 'energy rising'),
      B(20, 'Since this video started, you have moved ten thousand kilometres.', 'shock', 'flare', 'hit it, then stop'),
    ],
    loopLine: 'And you felt nothing. Watch it again. You will travel ten thousand more.',
    videoTitle: 'You Are Moving Faster Than A Bullet Right Now',
    description: 'You have never been still. Earth spins, orbits at ~30 km/s, and the whole system moves at roughly 550 km/s relative to the cosmic microwave background.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['earth rotation', 'milky way', 'physics', 'space facts', 'astronomy', 'mind blowing facts', 'science shorts', 'universe', 'space', 'shorts'],
    caption: 'You moved 10,000 km watching this. #space #physics #shorts #SpaceSpidey',
    pinnedComment: 'You just travelled 10,000 km. Where do you wish it had taken you?',
    factCheck: 'Rifle bullet ~1 km/s; Earth orbital speed ~30 km/s; motion vs CMB ~550 km/s, giving ~11,000 km in 20 s.',
    postmortem: 'v1 buried the payoff in the fourth beat and used three abstract speeds. v2 puts the bullet in the first four words and keeps exactly one comparison running through the whole script.',
    whyItWorks: 'One relatable anchor replaces three unfeelable numbers, the final beat makes the fact happen to the viewer during the video, and the loop line turns a rewatch into a physical event.',
  },
  {
    id: 3, number: 3, pillar: 'launch', publishOrder: 3, status: 'reshoot',
    title: 'LAUNCH 3 · The Prettiest Planet Rains Glass', world: 'derelict-station', durationSec: 28, mood: 'urgent',
    firstFrame: 'IT RAINS SIDEWAYS',
    hook: 'The prettiest planet in space wants you dead.',
    beats: [
      B(0, 'The prettiest planet in space wants you dead.', 'neutral', 'none', 'calm, almost fond'),
      B(4, 'From far off it looks like one calm blue ocean. Bluer than Earth.', 'scan', 'zoom', 'looking at a memory'),
      B(11, 'There is no water on it. None. That blue is glass.', 'narrow', 'static', 'tone turns'),
      B(18, 'Molten glass, thrown by wind seven times faster than sound.', 'shock', 'shake', ''),
      B(24, 'It never lands. It rains sideways. Forever.', 'anger', 'glitch', 'flat. cold. stop.'),
    ],
    loopLine: 'Now look at that pretty blue again. Still want to go?',
    videoTitle: 'The Prettiest Planet In Space Rains Glass Sideways',
    description: 'HD 189733b is cobalt blue from silicate glass clouds, with winds near 8,700 km/h and temperatures around 930C. The blue is not water.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['exoplanet', 'hd 189733b', 'planets', 'space facts', 'astronomy', 'scary space', 'science shorts', 'universe', 'space', 'shorts'],
    caption: 'The prettiest planet rains glass. Sideways. #exoplanet #space #shorts',
    pinnedComment: 'Ten seconds on the surface, fully protected, one look up. Do you go? Yes or no.',
    factCheck: 'HD 189733b: cobalt-blue from silicate (glass) clouds, ~8,700 km/h winds, ~930C (Hubble/ESA).',
    postmortem: 'v1 was close but the catalog number and the calm middle section cost the spike. v2 keeps every beat under twelve words and puts "it rains sideways" last, where the quote can be lifted.',
    whyItWorks: 'Beauty-to-horror inversion in six words a child understands, no unpronounceable names in the audio, and a closing dare that sends the viewer back to the opening shot.',
  },
  {
    id: 4, number: 4, pillar: 'launch', publishOrder: 4, status: 'reshoot',
    title: 'LAUNCH 4 · Something Called Earth. Once.', world: 'derelict-station', durationSec: 29, mood: 'urgent',
    firstFrame: '72 SECONDS. ONCE.',
    hook: 'Earth got one phone call from space. It lasted seventy-two seconds.',
    beats: [
      B(0, 'Earth got one phone call from space. Seventy-two seconds long.', 'neutral', 'none', 'whisper energy, dead still'),
      B(6, 'One telescope, one night in 1977. Then it was gone.', 'scan', 'none', ''),
      B(12, 'The man on shift circled it in red pen and wrote one word. Wow.', 'neutral', 'zoom', ''),
      B(19, 'Earth has listened for it every night since. For fifty years. Nothing.', 'sad', 'static', 'let the silence sit'),
      B(25, 'I heard it out here. And this time it said a word.', 'narrow', 'glitch', 'cold. hold the lens.'),
    ],
    loopLine: 'It said Earth. So tell me. Who called you first?',
    videoTitle: 'Something Called Earth In 1977. It Never Called Back.',
    description: 'The Wow! signal: 15 August 1977, Big Ear telescope, 72 seconds, ~30 sigma above background at 1420 MHz. Never re-detected, never explained.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['wow signal', 'seti', 'aliens', 'space mystery', 'unexplained', 'radio signal', 'space facts', 'science shorts', 'universe', 'shorts'],
    caption: 'It called once in 1977. Then silence. #wowsignal #aliens #space #shorts',
    pinnedComment: 'Who called? Star, machine, or someone. One word. Top answer gets a transmission.',
    factCheck: 'Wow! signal: 15 Aug 1977, Big Ear, 72 s, ~30 sigma at 1420 MHz; never re-detected.',
    postmortem: 'v1 said "a telescope heard one huge signal", which is a fact. v2 says "Earth got one phone call", which is a story. Same information, one of them survives the swipe.',
    whyItWorks: 'The phone-call metaphor is instantly human with zero jargon, every beat is under twelve words, and the final beat plus loop line turn a true event into a serialized cliffhanger. This is the subscriber converter.',
  },
  {
    id: 5, number: 5, pillar: 'launch', publishOrder: 5, status: 'reshoot',
    title: 'LAUNCH 5 · Ten Thousand Galaxies Are Missing', world: 'nebula-drift', durationSec: 28, mood: 'somber',
    firstFrame: '10,000 vs 60',
    hook: 'Ten thousand galaxies should be here. We found sixty.',
    beats: [
      B(0, 'Ten thousand galaxies should be in this patch of sky. We found sixty.', 'neutral', 'none', 'slow, heavy'),
      B(7, 'Light needs three hundred million years just to cross the hole.', 'scan', 'zoom', ''),
      B(13, 'Nobody can explain where the rest went. Nobody.', 'narrow', 'none', 'let it land'),
      B(19, 'From the middle of it, your entire night sky would be black.', 'sad', 'static', ''),
      B(24, 'Imagine looking up your whole life and seeing nothing at all.', 'shock', 'pulse', 'quiet horror'),
    ],
    loopLine: 'Someone in that dark thinks they are alone in the universe. So do you.',
    videoTitle: 'Ten Thousand Galaxies Are Missing And Nobody Knows Why',
    description: 'The Bo\u00f6tes Void is roughly 330 million light-years across and holds about 60 known galaxies where thousands would be expected. Discovered 1981.\n\nNew signal every 48 hours. Follow the signal.',
    tags: ['bootes void', 'void', 'galaxies', 'space mystery', 'dark matter', 'cosmology', 'space facts', 'science shorts', 'universe', 'shorts'],
    caption: '10,000 galaxies should be there. Sixty are. #space #mystery #shorts',
    pinnedComment: 'A sky with zero stars for your whole life. Peaceful or unbearable? Pick one.',
    factCheck: 'Bo\u00f6tes Void ~330 Mly across, ~60 known galaxies against thousands expected for the volume (discovered 1981).',
    postmortem: 'v1 opened on "a giant piece of the universe is almost empty" — vague, no number, no stakes. v2 opens on the two numbers that are the entire video, and the unpronounceable name never enters the audio.',
    whyItWorks: '"10,000 versus 60" is a whole mystery in two numbers anyone can hold, and the final line turns cosmology into loneliness, which is the emotion that gets space content shared.',
  },
];

/* The five already-published videos take numbers 1-5, so the log matches what
   is actually live on the channel. The 30 unshot scripts are 6-35. */
TRANSMISSIONS.unshift(...LAUNCH_SEQUENCE);

/* THE COUNT, so it is never ambiguous again:
     #1-5   — already published. Weak hooks. Marked `status: 'reshoot'`.
     #6-35  — 30 new scripts, none shot yet. This is the real queue.
     total  — 35 entries in the log.

   Recommended publish order for the new 30. NOT numerical order: this is
   sorted by how little the viewer needs to already know, because a cold
   audience will not sit through setup. Every entry is a script `number`. */
export const PUBLISH_ORDER = [
  8,  14, 12, 13, 7,  11, 6,  9,  10, 15,   // no prior knowledge needed — lead with these
  34, 35, 33, 24, 25, 16, 17, 20, 18, 19,   // trend + lore + the easier mysteries
  21, 22, 23, 26, 27, 28, 29, 30, 31, 32,   // heavier physics and long-form lore, once viewers return
];

/* Why #8 ("You Have Never Seen The Sky") is the first thing you publish:
     - needs zero prior knowledge. Everyone has looked up at night.
     - its loop is physical — the closing line sends the viewer outside, and
       going outside sends them back to the video. That is a real rewatch,
       which is the single strongest Shorts signal available.
     - the pinned comment answers in one word, so hour-one comment velocity
       (which sets the reach ceiling) is as cheap as it can possibly be.
     - "night sky" and "stars" are high-volume evergreen searches, so it keeps
       earning long after the initial push dies. */
export const FIRST_PUBLISH = 8;

/* Channel identity. Handles checked for spellability (say it once, type it
   right), search collision, and merch/series headroom. */
export const CHANNEL_KIT = {
  name: 'SpaceSpidey',
  displayName: 'SpaceSpidey',
  handles: ['@SpaceSpidey', '@SpaceSpideyy', '@SpaceSpideyOfficial', '@SpaceSpideyTransmits', '@RealSpaceSpidey'],
  nameRule: 'Always written SpaceSpidey — one word, both S capital. Never SPACESPIDEY, never Spacespidey, never Space Spidey.',
  tagline: 'Transmissions from somewhere past your sky.',
  bio: 'I am SpaceSpidey. My suit was woven from the web between galaxies. New transmission every 48 hours.',
  uploadCadence: 'One Short every 48 hours, same hour every time. Never miss a slot.',
  descriptionFooter: '\n\nNew signal every 48 hours. Follow the signal.',
  hashtagCore: ['#SpaceSpidey', '#space', '#shorts'],
  pinnedCommentRule: 'Pin within 60 seconds of publishing, then reply to the first ten comments within the first hour.',
};

export const EMOTE_TO_EXPR = {
  neutral: 'calm', smirk: 'smirk', anger: 'fury', sad: 'narrow',
  scan: 'calm', surge: 'shock', glitch: 'fury', shock: 'shock', narrow: 'narrow',
};
